### ISSUE TITLE
Add selenium support

### ISSUE THREAD

**Issue by VinciGit00** [ScrapeGraphAI/Scrapegraph-ai#171]
**Is your feature request related to a problem? Please describe.**
Add a check for looking to use async hromium loader or selenium

**Comment by fmelihh** [comment]
@lurenss I can work on this feature. Can you assing this feature to me?

**Comment by VinciGit00** [comment]
did it

**Comment by VinciGit00** [comment]
pls, can u do as fast as possible? we cannot stay up date on the features

**Comment by fmelihh** [comment]
I will complete it as quickly as possible @VinciGit00

**Comment by VinciGit00** [comment]
Thx

**Comment by nate-walter** [comment]
I’m interested in this feature too. How is it coming, if you don’t mind me asking.

**Comment by VinciGit00** [comment]
Hi, if you can help us it would be greatly

**Comment by SwapnilSonker** [comment]
Hey, @VinciGit00, I can work on this issue as I have done scripting and applications using Selenium. Will you please assign me this issue? If it is not resolved, I would love to help you out on this.

**Comment by VinciGit00** [comment]
Hi @SwapnilSonker I added you

**Comment by SwapnilSonker** [comment]
may I get a detailed feature requirements analysis as it would be helpful for me to develop it then?
@VinciGit00

**Comment by SwapnilSonker** [comment]
https://github.com/ScrapeGraphAI/Scrapegraph-ai/pull/846

here is the PR that i have created pls review it and if there are checks then let me know.
I have done this with best of my knowledge.
@VinciGit00

**Comment by SwapnilSonker** [comment]
@VinciGit00 added the example in example/extras with detailed explanation and robust error handling cases.
If anything more needs to be done, pls let me know.

**Comment by VinciGit00** [comment]
hi,I think is ok now. in the next day I will make the new release
