### ISSUE TITLE
 asyncio.run() cannot be called from a running event loop

### ISSUE THREAD

**Issue by kkarkos** [ScrapeGraphAI/Scrapegraph-ai#179]
Hi there,

trying to get SmartScraperGraph running on Fast-API. 

```
@app.post("/crawl")
async def crawl(request: Request):
    data = await request.json() 
    url = data.get('url')   

    try:  
        smart_scraper_graph =  SmartScraperGraph(
            prompt="List me all the articles",
            # also accepts a string with the already downloaded HTML code
            source=url,
            config=graph_config
        )

        result = smart_scraper_graph.run()

        print(result)

        # Access the URL field
        return result
    except Exception as e:
        print(f"Error in crawl: {e}")
        return None

```
Config
```
`graph_config = {
    "llm": {
         "model": "ollama/llama3",
        "temperature": 0,
        "format": "json",  # Ollama needs the format to be specified explicitly
        "base_url": "http://localhost:11434",  # set ollama URL arbitrarily
    },
    "embeddings": {
        "model": "ollama/nomic-embed-text",
        "base_url": "http://localhost:11434",  # set ollama URL arbitrarilyURL
    }
}`
```
Error:
```
Error in crawl: asyncio.run() cannot be called from a running event loop
/Users/konrad/Documents/Projects/product-spider/apps/service/main.py:171: RuntimeWarning: coroutine 'AsyncChromiumLoader.ascrape_playwright' was never awaited

```
Any idea? Thanks

**Comment by PeriniM** [comment]
Hey there, yes `Playwright` uses `asyncio` ander the hood so probably you are trying to run an asyncio routine inside another one (your async crawl method).
Right now the .rnu method doeesn't include a way to handle asynchronous calls but since it is a requested feature we will add it :)

Also we will include other web driver like the one provided by Selenium

**Comment by Kingki19** [comment]
> Hey there, yes `Playwright` uses `asyncio` under the hood so probably you are trying to run an asyncio routine inside another one (your async crawl method). Right now the .rnu method doeesn't include a way to handle asynchronous calls but since it is a requested feature we will add it :)

Hi, @PeriniM. Thanks for give explanation to this error. But what happen if i don't use `asyncio` in my code and get the same error like in this issue:
`RuntimeError: asyncio.run() cannot be called from a running event loop`

I try to run this code in Google Collab and get same error, here's my code: ( I actually copy it from one of your script 👍 )

```python
""" 
Basic example of scraping pipeline using SmartScraper
"""

import os
from dotenv import load_dotenv
from scrapegraphai.utils import prettify_exec_info
from scrapegraphai.graphs import SmartScraperGraph
load_dotenv()

from google.colab import userdata
gemini_key = userdata.get('Gemini_api_key') # To access my gemini api key in Google Environment

# ************************************************
# Define the configuration for the graph
# ************************************************

graph_config = {
    "llm": {
        "api_key": gemini_key,
        "model": "gemini-pro",
    },
}

# ************************************************
# Create the SmartScraperGraph instance and run it
# ************************************************

smart_scraper_graph = SmartScraperGraph(
    prompt="List me all the news with their description.",
    # also accepts a string with the already downloaded HTML code
    source="https://www.wired.com",
    config=graph_config
)

result = smart_scraper_graph.run()
print(result)

# ************************************************
# Get graph execution info
# ************************************************

graph_exec_info = smart_scraper_graph.get_execution_info()
print(prettify_exec_info(graph_exec_info))
```

Can you explain it why? Thank you

**Comment by Armando123x** [comment]
I have the same problem 

```
[ipython-input-3-d9d43c78117e>](https://localhost:8080/#) in <cell line: 28>()
     26 )
     27 
---> 28 result = smart_scraper_graph.run()
     29 print(result)

5 frames
[/usr/lib/python3.10/asyncio/runners.py](https://localhost:8080/#) in run(main, debug)
     31     """
     32     if events._get_running_loop() is not None:
---> 33         raise RuntimeError(
     34             "asyncio.run() cannot be called from a running event loop")
     35
```

**Comment by VinciGit00** [comment]
Pls update to the new version

**Comment by Shivansh-yadav13** [comment]
Hello @VinciGit00 I just installed and I'm getting the same error, I'm running the example from the website, 
I'm using conda env and on python  3.10.14
```py
import os
from dotenv import load_dotenv
from scrapegraphai.graphs import SmartScraperGraph
from scrapegraphai.utils import prettify_exec_info

load_dotenv()

openai_key = os.getenv("OPENAI_APIKEY")

graph_config = {
   "llm": {
      "api_key": openai_key,
      "model": "gpt-3.5-turbo",
   },
}

# ************************************************
# Create the SmartScraperGraph instance and run it
# ************************************************

smart_scraper_graph = SmartScraperGraph(
   prompt="List me all the projects with their description.",
   # also accepts a string with the already downloaded HTML code
   source="https://perinim.github.io/projects/",
   config=graph_config
)

result = smart_scraper_graph.run()
print(result)
```

**Comment by me-tetr** [comment]
Hey - I ran into smth similar while trying to wrap the smart scraper graph with some fastapi endpoints - what worked for me was to wrap the whole thing with  run_in_threadpool from starlette.concurrency - running version 1.2.3

**Comment by Kingki19** [comment]
> Hey - I ran into smth similar while trying to wrap the smart scraper graph with some fastapi endpoints - what worked for me was to wrap the whole thing with run_in_threadpool from starlette.concurrency - running version 1.2.3

Please give the example code

**Comment by Datarambler** [comment]
even I have the same error. Can you help with the exact code instructions to resolve this issue?

**Comment by philprime** [comment]
Encountering this issue too, while trying to run the graph from an async function (in my case a NATS event handler), I found the following workaround.

Basically it executes the asyncio event loop on another thread, but waits for the executing in the current event loop.

```python
import asyncio
from concurrent.futures import ThreadPoolExecutor

executor = ThreadPoolExecutor()

async def run_blocking_code_in_thread(blocking_func, *args, **kwargs):
    loop = asyncio.get_event_loop()
    return await loop.run_in_executor(executor, blocking_func, *args, **kwargs)
    
async def your_async_method():
    smart_scraper_graph = SmartScraperGraph(
        prompt=...,
        source=...,
        config=...
    )
    result = await run_blocking_code_in_thread(smart_scraper_graph.run)
```

Not sure if there are any downsides using this approach, as I am fairly new to working with Python event loops. Looking forward to built-in support

**Comment by alexauvray** [comment]
> please add the all the code

Updated my previous message

**Comment by alexauvray** [comment]
> please add the all the code

Any idea?

**Comment by Giustino98** [comment]
I am having the same error of this thread when trying to execute the code with Azure OpenAI configuration. This is my code:

```
from langchain_openai import AzureChatOpenAI, AzureOpenAIEmbeddings
import os

os.environ["AZURE_OPENAI_ENDPOINT"] = "...."
os.environ["AZURE_OPENAI_API_KEY"] = "..."

llm_model_instance = AzureChatOpenAI(
    azure_deployment="...",
    openai_api_version="...",
    temperature=0
)

embedder_model_instance = AzureOpenAIEmbeddings(
    azure_deployment="...",
    openai_api_version="...",
)

graph_config = {
    "llm": {
        "model_instance": llm_model_instance
    },
    "embeddings": {
        "model_instance": embedder_model_instance
    }
}

smart_scraper_graph = SmartScraperGraph(
    prompt="List me all the projects with their descriptions",
    # also accepts a string with the already downloaded HTML code
    source="https://perinim.github.io/projects",
    config=graph_config
)

result = smart_scraper_graph.run()
print(result)

**Comment by bensonbs** [comment]
Avoid to use `.ipynb` can fixed it.

**Comment by AliHaider20** [comment]
Run this before the above code.

```
import nest_asyncio
nest_asyncio.apply()
```

**Comment by xjtupy** [comment]
> even I have the same error. I have tried to add the following:
> 
> import nest_asyncio nest_asyncio.apply() result = smart_scraper_graph.run()
> 
> after which I'm getting a new error:
> 
> Exception: Connection closed while reading from the driver. Please help how to resolve this.



> even I have the same error. I have tried to add the following:
> 
> import nest_asyncio nest_asyncio.apply() result = smart_scraper_graph.run()
> 
> after which I'm getting a new error:
> 
> Exception: Connection closed while reading from the driver. Please help how to resolve this.

**Comment by giuliastro** [comment]
Any news on the solution? I tried all of the above but on my Fastapi backend it doesn't seem to work. Thank you.
