### ISSUE TITLE
Feature Request: Utilize Vision API for scraping

### ISSUE THREAD

**Issue by mikewolfd** [ScrapeGraphAI/Scrapegraph-ai#197]
Offer a node to scrape by taking a full-size image of the website and pass that through to a Vision Inference service.

I've found that this solution results in a more contextually complete response.

**Comment by PeriniM** [comment]
Hey @mikewolfd right now we have only one ImageToText node which uses gpt-4 vision [here](https://github.com/VinciGit00/Scrapegraph-ai/blob/main/scrapegraphai/nodes/image_to_text_node.py).
It takes a URL of the image as input. We are planning to implement other multi-modal models such as llava

**Comment by VinciGit00** [comment]
hi, we have this feature to the screenshot scraper
