### ISSUE TITLE
Not able to run Anthropic Claude models. 

### ISSUE THREAD

**Issue by paarthmadan-avataar** [ScrapeGraphAI/Scrapegraph-ai#402]
KeyError                                  Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/scrapegraphai/graphs/abstract_graph.py](https://localhost:8080/#) in _create_llm(self, llm_config, chat)
    181             try:
--> 182                 self.model_token = models_tokens["claude"][llm_params["model"]]
    183             except KeyError as exc:

KeyError: 'claude-3-haiku-20240307'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
3 frames
[/usr/local/lib/python3.10/dist-packages/scrapegraphai/graphs/abstract_graph.py](https://localhost:8080/#) in _create_llm(self, llm_config, chat)
    182                 self.model_token = models_tokens["claude"][llm_params["model"]]
    183             except KeyError as exc:
--> 184                 raise KeyError("Model not supported") from exc
    185             return Anthropic(llm_params)
    186         elif "ollama" in llm_params["model"]:

KeyError: 'Model not supported'

**Comment by VinciGit00** [comment]
please update

**Comment by paarthmadan-avataar** [comment]
Can you share the a correct claude api model names to key in the graph config?

**Comment by GRiDD** [comment]
Still getting this error. I tried with 1.7.4 and 1.8.0-beta.1

    self.model_token = models_tokens["claude"][llm_params["model"]]
KeyError: 'claude-3-haiku-20240307'

**Comment by VinciGit00** [comment]
hi, please install the new version, we added that model.
