### ISSUE TITLE
split unit testing from src

### ISSUE THREAD

**Issue by DiTo97** [ScrapeGraphAI/Scrapegraph-ai#404]
following lines should be moved to a unit testing file or be wrapped with main guards:

https://github.com/VinciGit00/Scrapegraph-ai/blob/62fdbcca52012c34d714232b1f6987c83e841c62/scrapegraphai/utils/parse_state_keys.py#L106

I haven't checked the rest, but there might be other similar instances throughout the code base.

**Comment by VinciGit00** [comment]
Hi please update to the new version
