### ISSUE TITLE
Result json truncated attachments for long attachment list

### ISSUE THREAD

**Issue by salman-khandu** [ScrapeGraphAI/Scrapegraph-ai#414]
model : gpt-4o
I have html where there are many attachment (around 110 but it got only 69) so i use prompt like "Extract title, abstract, published date, all attachments as array of object with text and url link as a field and related content as array of objects with text and url link as field" what i see in result is all attachments are not there and last url in attachments i see truncated like https://test.com/23232323/file-201 where actual url is https://test.com/23232323/file-2024-result-test.pdf . is there any reason why data is truncated ?

**Comment by VinciGit00** [comment]
Hi please update to the new version
