### ISSUE TITLE
ImportError: cannot import name 'Required' from 'typing' (/usr/local/lib/python3.11/typing.py)

### ISSUE THREAD

**Issue by sunejay** [ScrapeGraphAI/Scrapegraph-ai#415]
When I run this code

`from scrapegraphai.graphs import SmartScraperGraph
import nest_asyncio

graph_config = {
    "llm": {
        "model": "ollama/mistral",
        "temperature": 0,
        "format": "json",  # Ollama needs the format to be specified explicitly
        "base_url": "http://localhost:11434",  # set Ollama URL
    },
    "embeddings": {
        "model": "ollama/nomic-embed-text",
        "base_url": "http://localhost:11434",  # set Ollama URL
    }
}
smart_scraper_graph = SmartScraperGraph(
    prompt="List me all items",
    # also accepts a string with the already downloaded HTML code
    source="https://www.url.com",
    config=graph_config
)

nest_asyncio.apply()

result = smart_scraper_graph.run()
print(result)
`

I got the following error

![scrapegraphai-error-2024-06-28](https://github.com/VinciGit00/Scrapegraph-ai/assets/44901635/2e37deb7-6c93-48fb-a980-22475911a9ba)

**VERSIONS**
Ubuntu - 20.04
Scrapegraphai - 1.7.4

**Comment by VinciGit00** [comment]
have you tried to run without asyncio?

**Comment by VinciGit00** [comment]
hi please update to the new version
