### ISSUE TITLE
Add Vertex AI Integration

### ISSUE THREAD

**Issue by PeriniM** [ScrapeGraphAI/Scrapegraph-ai#423]
**Is your feature request related to a problem? Please describe.**
No Vertex AI support

**Describe the solution you'd like**
Add a new LLM class that integrates Vertex AI, Langchain [docs](https://python.langchain.com/v0.2/docs/integrations/chat/google_vertex_ai_palm/)

**Describe alternatives you've considered**
Directly pass the model_instance in the graph_config, like [here](https://github.com/VinciGit00/Scrapegraph-ai/blob/main/examples/azure/smart_scraper_azure.py)

**Comment by VinciGit00** [comment]
I will also add embeddings :)
