### ISSUE TITLE
Ollama JSON format is used for creating search query

### ISSUE THREAD

**Issue by AmosDinh** [ScrapeGraphAI/Scrapegraph-ai#433]
**Describe the bug**
When using Ollama and specifying that JSON output is wanted, the same LLM is used for creating the search query and for the latter operations.
But we do not want the search query to be in JSON format.

User query: "Extract information regarding Macbook Pro m1 versions (year, price, specs, etc.). Be specific with the versions and make sure to include all. List every model configuration separately".

LLM processes now and returns this as search query:
{"MacBook Pro M1 versions" 
But what we would like to search is only : MacBook Pro M1 versions (without " and {)

**Comment by VinciGit00** [comment]
have you tried to switch llm?

**Comment by AmosDinh** [comment]
Happens for the lama3 model and gemma2 as well
config looks like this:

graph_config = {
     "llm": {
        "model": "ollama/gemma2:latest",
        "temperature": 0,
        "format": "json",  # Ollama needs the format to be specified explicitly
        "base_url": "http://localhost:11434",  # set Ollama URL
    },
    "embeddings": {
        "model": "ollama/nomic-embed-text",
        "base_url": "http://localhost:11434",  # set ollama URL arbitrarily
    },
    "max_results": 5,
    "verbose": True,
    }

**Comment by AmosDinh** [comment]
Hello, can you confirm this is an issue? Or is it the supposed behavior?

Maybe I can fix it if needed

**Comment by VinciGit00** [comment]
Yes please can you try to fix it?

**Comment by f-aguzzi** [comment]
Thanks @AmosDinh for fixing this
