### ISSUE TITLE
Strange results

### ISSUE THREAD

**Issue by kitsune0n** [ScrapeGraphAI/Scrapegraph-ai#435]
**Describe the bug**
Trying to make promt with result like an content category
when test it with source like in example     source="https://perinim.github.io/projects" all works fine
`Result: {'Category': 'Portfolio'}`
when change it to any other
have result with urls or videoThumbnails 
like : 
`Result: {'urls': ['https://www.wired.com/', 'https://sp.analytics.yahoo.com/sp.pl?a=10000&d=Thu%2C%2004%20Jul%202024%2014%3A47%3A46%20GMT&n=-3d&b=WIRED%20-%20The%20Latest%20in%20Technology%2C%20Science%2C%20Culture%20and%20Business%20%7C%20WIRED&.yp=10200402&f=https%3A%2F%2Fwww.wired.com%2F&enc=UTF-8&yv=1.15.1&ec=PageView&et=PageView&tagmgr=gtm' ......`

**To Reproduce**
smart_scraper_graph = SmartScraperGraph(
    prompt="What is website content category ?",
    source="https://www.wired.com/",
    config=graph_config
)

**Desktop (please complete the following information):**
 - Win11
 - remote ollama (debian12)

**Comment by luckylokki** [comment]
the same issue

**Comment by VinciGit00** [comment]
try to make experiments with other llm models, for example it could work with gpt4o
