### ISSUE TITLE
Stuck at "(updated chunks metadata)"

### ISSUE THREAD

**Issue by elmoBG8** [ScrapeGraphAI/Scrapegraph-ai#453]
I'm using the latest version. 
Putting to True Verbose the configuration, I can see that it stucks at "(updated chunks metadata)" even if I'm using a model from Groq... Nothing happens, it seems.

I'm running the example you provide in the readme with another URL.

**Comment by VinciGit00** [comment]
hi, please update to the new beta

**Comment by elmoBG8** [comment]
Okay, thank you very much!
