### ISSUE TITLE
Dude...what are the supported Ollama models???

### ISSUE THREAD

**Issue by aleenprd** [ScrapeGraphAI/Scrapegraph-ai#455]
As per the title, I keep running into the error `ValueError: Model provided by the configuration not supported`. I think the logging should provide a list of valid models. And/or this should be made evident in the documentation

**Comment by VinciGit00** [comment]
hi the models supported are: [https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/main/scrapegraphai/helpers/models_tokens.py](https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/main/scrapegraphai/helpers/models_tokens.py) . It' s in this page of the documentation [https://scrapegraph-doc.onrender.com/docs/Examples/models](https://scrapegraph-doc.onrender.com/docs/Examples/models)

**Comment by ZewenShen** [comment]
@VinciGit00 Is it possible to use a specified quantized version of an Ollama model? For example, qwen2.5:32b-instruct-q5_K_M
