### ISSUE TITLE
does it support custom embeddings

### ISSUE THREAD

**Issue by riddle911** [ScrapeGraphAI/Scrapegraph-ai#460]
Silicon Cloud offers a vast array of free models, including Large Language Models (LLMs) and vector models, with support for online invocation. I would like to know what methods can be used to support the invocation of their API.
Below is the example of the api.
[https://docs.siliconflow.cn/reference/createembedding-1](url)

**Comment by VinciGit00** [comment]
Hi, we will add it if it is possible

**Comment by f-aguzzi** [comment]
The current implementation of ScrapeGraph uses LangChain as a wrapper to exchange data with external LLM providers. Silicon Cloud is not currently supported by LangChain, so adding it within ScrapeGraph will require a custom-made wrapper. I'll work on it (@VinciGit00 thinks it might actually be a good thing to bypass LangChain in the long run) but it might take a while. We'll keep you updated.
