### ISSUE TITLE
Problem extracting urls and image urls using the FetchNode

### ISSUE THREAD

**Issue by DenisMarasescu** [ScrapeGraphAI/Scrapegraph-ai#464]
### Discussed in https://github.com/ScrapeGraphAI/Scrapegraph-ai/discussions/452

<div type='discussions-op-text'>

<sup>Originally posted by **DenisMarasescu** July 13, 2024</sup>
In the docusaurus mentioned in the readme (specifically https://scrapegraph-doc.onrender.com/docs/Nodes/fetch_html_node), it is shown that the fetch_node should return the fetched_content, the link_urls and the image_urls. 

Unfortunately, they are not. I wonder why and, especially, how can I retrieve the urls and the image urls without this function.</div>

**Comment by VinciGit00** [comment]
hi, we are adding a graph for that, the new version will have it

**Comment by VinciGit00** [comment]
ok please for extracting the links use this [https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/pre/beta/examples/openai/search_link_graph_openai.py](https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/pre/beta/examples/openai/search_link_graph_openai.py). You should use the new beta
