### ISSUE TITLE
Is "코리아노" a deliberate translation? 

### ISSUE THREAD

**Issue by bhyun-kim** [ScrapeGraphAI/Scrapegraph-ai#465]
I noticed the unnatural translation '코리아노' used in `README.md`. Could you confirm if this is deliberate? It's not a commonly used expression. You could use '한국어' instead.

If needed, I can make a PR to improve the Korean translation.

**Comment by VinciGit00** [comment]
yes, it was generated by the ai, if you can please fix it because we do not speak Korean
