### ISSUE TITLE
Using Nemotron from nvidia

### ISSUE THREAD

**Issue by DenisMarasescu** [ScrapeGraphAI/Scrapegraph-ai#479]
How can I use Nemotron from nvidia with the api key from them? They are OpenAI API compatible. Look at this link:
https://build.nvidia.com/nvidia/nemotron-4-340b-instruct

**Comment by VinciGit00** [comment]
cool! we will add it!

**Comment by VinciGit00** [comment]
hi please update to the new beta

**Comment by VinciGit00** [comment]
Now it's in the main
