### ISSUE TITLE
 it is not supported llama3.1:8b 

### ISSUE THREAD

**Issue by ComposerLM** [ScrapeGraphAI/Scrapegraph-ai#489]
**Additional context**
![图片](https://github.com/user-attachments/assets/890309e8-4ad6-46ab-a516-02e07d8100d1)
![图片](https://github.com/user-attachments/assets/d2ffaf03-c407-45a1-8a0a-37c44f1925c3)

**Comment by VinciGit00** [comment]
hi please update
