### ISSUE TITLE
Support for Embedding and LLM's hosted on AWS bedrock

### ISSUE THREAD

**Issue by ramammah** [ScrapeGraphAI/Scrapegraph-ai#492]
**Is your feature request related to a problem? Please describe.**
I Dont see documentation on how to use Models on AWS bedrock.

**Describe the solution you'd like**
A config Page where I Can provide AWS IAM credentials or may be this uses boto3 to accept instance profiles and call AWS bedrock invoke API to use models and embeddings

**Describe alternatives you've considered**
No Alternative

**Additional context**

**Comment by VinciGit00** [comment]
for bedrock look at these links: [https://github.com/ScrapeGraphAI/Scrapegraph-ai/tree/main/examples/bedrock](https://github.com/ScrapeGraphAI/Scrapegraph-ai/tree/main/examples/bedrock)
