### ISSUE TITLE
Support for firecrawl

### ISSUE THREAD

**Issue by AmosDinh** [ScrapeGraphAI/Scrapegraph-ai#493]
Would be interesting if support was added for firecrawl.ai.
They also allow to [self host](https://github.com/mendableai/firecrawl/blob/main/SELF_HOST.md) their service. 
Firecrawl allows for cleaner crawling, they handle pdf's as well as dynamic websites.

**Comment by AmosDinh** [comment]
I tested it and it is a lot faster than standard chromium.py. You can check for yourself here:
https://github.com/ScrapeGraphAI/Scrapegraph-ai/compare/pre/beta...AmosDinh:Scrapegraph-ai:pre/beta

you need to add a .env file like this (if self hosting):
FIRECRAWL_API_URL=http://localhost:3002
FIRECRAWL_API_KEY=YOUR_API_KEY_NOT_NEEDED

or if you want to quickly test out with the free tier of firecrawl:
FIRECRAWL_API_KEY=YOUR_API_KEY

you need to add this in the scrapegraphai configs:
 "loader_kwargs": {
        "scraping_backend': 'firecrawl'
    },
    
   future option would be to add arguments
   firecrawl_api_key and firecrawl_api_url to loarder_kwargs. 
   The langchain class unfortunately does not support passing the url as argument yet, i have submitted a pull request.
    
    
    e.g.:
    
    from scrapegraphai.graphs import SearchGraph
import os

def load_env(env_file='.env'):
    try:
        with open(env_file, 'r') as file:
            for line in file:
                line = line.strip()
                if line and not line.startswith('#'):
                    key, value = line.split('=', 1)
                    print(key, value)
                    os.environ[key] = value
    except FileNotFoundError:
        print(f"Warning: {env_file} file not found.")
    except Exception as e:
        print(f"Error reading {env_file}: {e}")

# Load the environment variables
load_env()

# Verify that the environment variables are set
print(f"API URL: {os.environ.get('FIRECRAWL_API_URL')}")
print(f"API Key: {os.environ.get('FIRECRAWL_API_KEY')}")

# Define the configuration for the graph
graph_config = {
     "llm": {
        "model": "ollama/llama3.1",
        "temperature": 0,
        "format": "json",  # Ollama needs the format to be specified explicitly
        "base_url": "http://localhost:11434",  # set Ollama URL
    },
    "embeddings": {
        "model": "ollama/nomic-embed-text",
        "base_url": "http://localhost:11434",  # set ollama URL arbitrarily
    },
    "max_results": 5,
    "verbose": True,
    "headless":True,
    "loader_kwargs": {
        # "proxy" : {
        #     "server": "broker",
        #     "criteria": {
        #         "anonymous": True,
        #         "secure": True,
        #         #"countryset": {"IT"},
        #         "timeout": 10.0,
        #         "max_shape": 3
        #     },
        # },
        'scraping_backend': 'firecrawl'
    },
}



# Create the SearchGraph instance
search_graph = SearchGraph(
    prompt="Extract information regarding Macbook Pro m1 versions (year, price, specs, etc.). Be specific with the versions and make sure to include all. List every model configuration separately",
    config=graph_config
)

# Run the graph and print the result
result = search_graph.run()
print(result)

**Comment by AmosDinh** [comment]
Not sure if you want to add firecrawl-py to requirements.txt. And docs could be updated. 
are you interested in this?

**Comment by VinciGit00** [comment]
yes, we could be interested

**Comment by AmosDinh** [comment]
Ok great, although I won't be able to integrate everything. I don't have the full overview over features in firecrawl as well as scrapegraph. So e.g. besides the changes I made in my branch, you could integrate the pdf extraction etc. 

Generally, this should be beneficial to anyone, since it is a lot faster to crawl with their method. I think they use playwright internally as well but am not sure why it is faster.

**Comment by f-aguzzi** [comment]
Also, we use [Rye](https://rye.astral.sh/) as our python project configuration tool. If you want to add Firecrawl as a dependency, either add it to the `pyproject.toml` file at the root of the project, or through the Rye CLI. `requirements.txt` is built from `pyproject.toml` using a script. Sorry that this isn't specified anywhere - we need to update the contributing guidelines

**Comment by angelotc** [comment]
why not just use jina? it's free and easier to use

**Comment by f-aguzzi** [comment]
Closing this issue, as the pull request was rejected by the repo owners.
