### ISSUE TITLE
This code cause wrong when use AzureOpenAI api

### ISSUE THREAD

**Issue by EthanLI24** [ScrapeGraphAI/Scrapegraph-ai#498]
https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/d6c58396a19a85e4c94902a3c66ffa46dcdd3f27/scrapegraphai/graphs/abstract_graph.py#L160

I use ‘azrure/gpt’ in my code, and then I found that this line of judgment logic will cause the code to run into the openai api because the judgment logic of 'gpt-' precedes 'azure' and I am not sure whether other apis will encounter similar problems.

**Comment by f-aguzzi** [comment]
Could you please post your code, especially your `graph_config`?

We're refactoring the `AbstractGraph` (issue #497) at the moment, so if the issue persists we might fix it there. It might just be a matter of moving the `Azure` block before the `OpenAI` block in the `AbstractGraph` code.

In the meanwhile, thanks for using ScrapeGraphAI and for reporting this issue.

**Comment by f-aguzzi** [comment]
Fixed it. Nevermind about the code example.

The fix will be published in the next beta, and this issue will close automatically then. Thanks again for reporting this bug.
