### ISSUE TITLE
Browser is closing before the website content is fully loaded

### ISSUE THREAD

**Issue by antsanchez** [ScrapeGraphAI/Scrapegraph-ai#504]
**Describe the bug**
Using SmartScraperGraph, some websites which require JS rendering can't be scraped, since the browser is closed before the content of the website is completely loaded. 

**To Reproduce**
Code example:
```
graph_config = {
    "llm": {
        "api_key": openai_key,
        "model": "gpt-4o",
    },
    "verbose": False,
    "headless": False,
}

smart_scraper_graph = SmartScraperGraph(
    prompt="Describe this job",
    source="https://apply.workable.com/gridware/j/D5272E4D2F/",
    config=graph_config,
)

result = smart_scraper_graph.run()
```

**Expected behavior**
The expected behaviour is the description of the job, but instead i get this:
`{"result":{"description":"NA"}}`

**Desktop (please complete the following information):**
 - OS: Amazon Linux, Mac OS
 - Browser: Chrome

**Comment by VinciGit00** [comment]
hi pls try with this [https://scrapegraph-doc.onrender.com/docs/Examples/slow_mo_](https://scrapegraph-doc.onrender.com/docs/Examples/slow_mo_)
