### ISSUE TITLE
Refactoring of the fetch node

### ISSUE THREAD

**Issue by VinciGit00** [ScrapeGraphAI/Scrapegraph-ai#506]
This [https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/main/scrapegraphai/nodes/fetch_node.py](class) should be refactored.
The switch blocks from line 104 to 162 should become ligthweigth

**Comment by vedovati-matteo** [comment]
I would like to do it

**Comment by VinciGit00** [comment]
thx
