### ISSUE TITLE
Using SmartScraperGraph with Azur gpt-4o-mini deplyoment

### ISSUE THREAD

**Issue by ismail-amouma** [ScrapeGraphAI/Scrapegraph-ai#508]
Hello everyone,

I've been using SmartGraphAI with the OpenAI API for a while, and now I'm switching to Azure. 

I want to know how to use it with Azure's GPT-4o deployment. Here is what I was using with OpenAI:

```python
graph_config = {
    "llm": {
        "api_key": os.getenv("OPENAI_API_KEY"),
        "model": "gpt-4o-mini",
    },
    "verbose": True,
    "headless": True,
}
```

Azure provided me with an endpoint and a key when I deployed the GPT-4o-mini model. How can I pass these to the configuration?

**Comment by VinciGit00** [comment]
hi please try with this example [https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/main/examples/azure/smart_scraper_azure.py](url)
