### ISSUE TITLE
`NameError: name 'input_data' is not defined` is raised when trying to use smart_scraper_graph.run()

### ISSUE THREAD

**Issue by appoks** [ScrapeGraphAI/Scrapegraph-ai#525]
**Describe the bug**
I'm receiving an `NameError: name 'input_data' is not defined` error when trying to use scrapegraph.
I've tryed both running on my machine and on the google collab example.

**To Reproduce**
1. Go to Google collab scrapegraphai
2. Execute all the steps needed
3. Execute the `result = smart_scraper_graph.run()` code cell

**Expected behavior**
ScrapeGraph should execute and return the results

**Screenshots**
![image](https://github.com/user-attachments/assets/1144a687-60ec-4d60-bccc-56ff69632063)

**Desktop (please complete the following information):**
 - OS: Google Collab env
 - Browser: Brave

**Comment by VinciGit00** [comment]
which version are you using?

**Comment by anth0nyhak1m** [comment]
Please specify to which version should we upgrade it to? I just installed the package using the directions which doesn't specify a version, I assume it should install the newest version. Also, do we need to upgrade playwright as well or just the scrapegraphai library.

**Comment by VinciGit00** [comment]
the latest one
