### ISSUE TITLE
OMP: Error #15: Initializing libiomp5md.dll, but found libomp140.x86_64.dll already initialized

### ISSUE THREAD

**Issue by ahworld22** [ScrapeGraphAI/Scrapegraph-ai#526]
I meet the  problem when I run my pycharm to train some modle , but I don't know how to solve it.I use windows11 ,and it seems that libomp140.x86_64.dll is in the flips of window,not anaconda.I see someone solve it by  updating #214 , but I don't know I should update which thing.

**Comment by ahworld22** [comment]
@VinciGit00

**Comment by VinciGit00** [comment]
ok please share the code

**Comment by ahworld22** [comment]
> ok please share the code

[train.zip](https://github.com/user-attachments/files/16569616/train.zip)

**Comment by ahworld22** [comment]
> > ok please share the code
> 
> [train.zip](https://github.com/user-attachments/files/16569616/train.zip)

I‘m updating my anaconda now,and I want to establish a new environment for this project to try again.

**Comment by Daniellin1207** [comment]
i meet the same problem, have you solved this? @ahworld22

**Comment by ahworld22** [comment]
> i meet the same problem, have you solved this? @ahworld22

Yes.I establish a new environmen for my project.

**Comment by f-aguzzi** [comment]
@ahworld22 can you confirm that it was only a problem with the environment? If so, we can close this issue
