### ISSUE TITLE
ImportError: cannot import name 'OpenAI' from 'scrapegraphai.models' (/usr/local/lib/python3.10/dist-packages/scrapegraphai/models/__init__.py)

### ISSUE THREAD

**Issue by angelotc** [ScrapeGraphAI/Scrapegraph-ai#534]
Trying to use the custom graph, and receiving the error. https://colab.research.google.com/drive/1sEZBonBMGP44CtO6GQTwAlL0BGJXjtfd?usp=sharing#scrollTo=eQLZJyg4uLUJ

**To Reproduce**
1. Run the cells under custom graph

**Expected behavior**
No errors. 

**Desktop (please complete the following information):**
- Brave + Google Colab

**Comment by angelotc** [comment]
I think this is incorrect import : 

from scrapegraphai.models import OpenAI

**Comment by VinciGit00** [comment]
Thx I will try to fix it

**Comment by VinciGit00** [comment]
it could be the error
