### ISSUE TITLE
Add support for other OpenAI models like gpt-4o-2024-08-06

### ISSUE THREAD

**Issue by sandeepchittilla** [ScrapeGraphAI/Scrapegraph-ai#550]
**Is your feature request related to a problem? Please describe.**
Missing some models from OpenAI like `gpt-4o-2024-08-06` 

**Describe the solution you'd like**
Add this to the `scrapegraphai/helpers/models_tokens.py` file

**Describe alternatives you've considered**
N/A

**Additional context**
I can raise a PR for this if you're okay with it @VinciGit00 (if this isn't already in the works)

**Comment by VinciGit00** [comment]
hi, we added in the pre/beta. Please update to the new version
