### ISSUE TITLE
Whether it can support llm models compatible with the open AI api protocol？

### ISSUE THREAD

**Issue by goasleep** [ScrapeGraphAI/Scrapegraph-ai#560]
**Is your feature request related to a problem? Please describe.**
I've encountered an issue where I wish to utilize language models from providers other than the mainstream ones like OpenAI, Anthropic, Google, etc., such as Moonlight and Tongyi Qianwen (not the Ollama local qwen model). I've found that these models are not supported because they are considered providers that are not officially recognized.

In reality, these language models are compatible with the OpenAI protocol, meaning they can be utilized with the OpenAI SDK. For instance, Moonlight uses the OpenAI SDK as demonstrated below:
``` python
from openai import OpenAI
 
client = OpenAI(
    api_key="MOONSHOT_API_KEY", 
    base_url="https://api.moonshot.cn/v1",
)
``` 

I would like ScrapeGraph-AI to support Moonshot's language model in a similar fashion, but upon reviewing the source code, I couldn't find any hooks or parameters to facilitate this. Consequently, I made a commit to add support for Moonlight (https://github.com/ScrapeGraphAI/Scrapegraph-ai/commit/3275001c9a258a0458ba0cf1db59719bb7949411), and I'm uncertain if there might be other issues arising from this change.

**Describe the solution you'd like**
I propose adding a parameter to override_provider to allow for the custom definition of the provider, enabling other language models to work with ScrapeGraph-AI. The configuration would look something like this:
```
graph_config = {
    "llm": {
        "model":"moonshot-v1-8k",
        "base_url": "https://api.moonshot.cn/v1", 
        "api_key": api_key
        "override_provider": "openai",
    },
}
```

**Describe alternatives you've considered**
I am open to the possibility of other solutions, but I am not entirely certain if all options have been explored.

**Other**
I am unsure of the impact of the aforementioned change and whether there are other aspects of the system that this change might affect. However, I have tested the example provided in the commit, and no issues were encountered.

I kindly request a review of this demo. If there are no problems, I am interested in taking on this task and would appreciate the opportunity to contribute by submitting a PR when appropriate.

**Comment by pathikb** [comment]
It works already. For example, for OpenRouter, I use:

graph_config = {
    "llm": {
        "api_key": "XX",
        "model": "gpt-4o-mini",
        "openai_api_base": "https://openrouter.ai/api/v1"
    },
    "verbose": True,
    "headless": False,
}

**Comment by goasleep** [comment]
> It works already. For example, for OpenRouter, I use:
> 
> graph_config = { "llm": { "api_key": "XX", "model": "gpt-4o-mini", "openai_api_base": "https://openrouter.ai/api/v1" }, "verbose": True, "headless": False, }

I try your solution and raise ValueError: Model provided by the configuration not supported
```
graph_config = {
    "llm": {
        "model":"moonshot-v1-8k",
        "openai_api_base": "https://api.moonshot.cn/v1",  
        "api_key": api_key
    },
    "verbose": True, 
    "headless": True
}
``` 

It seems you misunderstood me. Allow me to clarify: I have developed a custom language model known as 'customer_llm_model.' While this model is not recognized by OpenRouter or other multi-model platforms, it is designed to function in a manner similar to models like 'gpt-4'.

``` python
graph_config = {
"llm": {
"api_key": "XX",
"model": "cutomer_llm_model", # here 
"openai_api_base": "https://openrouter.ai/api/v1"
},
"verbose": True,
"headless": False,
}
```

**Comment by pathikb** [comment]
In my opinion, if your openai_api_base endpoint follows OpenAI API specs, I don't see why it wouldn't work considering OpenRouter works.

**Comment by goasleep** [comment]
> In my opinion, if your openai_api_base endpoint follows OpenAI API specs, I don't see why it wouldn't work considering OpenRouter works.

Take [this model](https://openrouter.ai/models/qwen/qwen-2-7b-instruct:free) example. you also get `ValueError: Model provided by the configuration not supported`

``` python 
graph_config = {
    "llm": {
        "model":"qwen/qwen-2-7b-instruct:free",
        "openai_api_base": "https://openrouter.ai/api/v1",  
        "api_key": api_key
    },
    "verbose": True,
    "headless": True
}
```

**Comment by f-aguzzi** [comment]
There's a system in place that automatically sets the size of the context window based on the name of the model. That's what's causing the error when trying to use an unsupported model. To bypass it, you can try passing a model instance directly:

```python
from langchain_openai import ChatOpenAI
# add all the other imports depending on the graph you're using

instance_config = {
    "model":"qwen/qwen-2-7b-instruct:free",
     "openai_api_base": "https://openrouter.ai/api/v1",  
     "api_key": api_key
}

llm_model_instance = ChatOpenAI(**instance_config)

graph_config = {
    "llm": {
        "model_instance": llm_model_instance
        "max_tokens": 4000
    },
    "verbose": True,
    "headless": True
}

# and then create and execute the graph
```

**Comment by f-aguzzi** [comment]
@goasleep by the way, if you want to contribute your changes to support Moonshot, feel free to open a pull request, and tag me in it. I'll handle the merging conflicts and make sure that your changes are integrated correctly.

Thanks to both you and @pathikb for contributing to the ScrapeGraph community.

**Comment by goasleep** [comment]
@f-aguzzi  Thank you for your solution. I later found it in the documentation, but it seemed a bit hard to find, so I added a section of the instructions in the documentation

**Comment by f-aguzzi** [comment]
Did it work? I didn't get the chance to test the instance example before posting it here.

I agree with you, this stuff isn't documented well enough. As you may have noticed, we have very basic, autogenerated docs on Read The Docs, frequently updated but not very detailed, and a less frequently updated, but handwritten, docs website on Render. Many features fall through the cracks of both websites and aren't put in the examples either. This is on our long to-do list of things to fix.
