### ISSUE TITLE
Cannot Recognise Ollama Models

### ISSUE THREAD

**Issue by qzc438** [ScrapeGraphAI/Scrapegraph-ai#566]
Dear Team,

In the graph_config, I use "model": "ollama/llama3:8b" (with the parameter specification), but ScrapeGraphAI cannot recognise this model.

Sincerely,
Zhangcheng Qiang

**Comment by goasleep** [comment]
Hello, would you help to offer any exceptions or errors?

**Comment by f-aguzzi** [comment]
We have a token dictionary containing the most common models for each provider, but we haven't updated the Ollama section in a while. We'll make an update and put it into the next beta.

Thanks for taking interest in our library and for reporting this.

**Comment by f-aguzzi** [comment]
Done. Use version 1.14.1b1 to get access to the updated version with llama3:8b support.

We'll close this issue as soon as the update gets released to the stable channel. Thanks again for reporting this.
