### ISSUE TITLE
AbstractGraph is broken once again

### ISSUE THREAD

**Issue by f-aguzzi** [ScrapeGraphAI/Scrapegraph-ai#572]
Despite it going through two rounds of refactoring, there's still something off with its logic.

Many model providers are duplicated. I think something might have gone wrong when merging. We need to fix it once again.

We need to be more careful with merge operations. This is not the first time that I see new code getting overwritten by older code from stale branches.

**Comment by VinciGit00** [comment]
ok now the updated beta has fixed it
