### ISSUE TITLE
ValueError: Model 'gemini-pro' is not supported

### ISSUE THREAD

**Issue by tahirs95** [ScrapeGraphAI/Scrapegraph-ai#575]
**Describe the bug**
ValueError: Model 'gemini-pro' is not supported

**To Reproduce**
graph_config = {
    "llm": {"api_key": GEMINI_API_KEY, "model": "gemini-pro"},
    "headless": False,   
}

Version: scrapegraphai==1.14.0

**Comment by VinciGit00** [comment]
Hi, we will fix it as soon as possible

**Comment by VinciGit00** [comment]
Hi, you should have done 
`
graph_config = {
"llm": {"api_key": GEMINI_API_KEY, "model": "google_genai/gemini-pro"},
"headless": False,
}
`
I will close the issuee but let me know if it works!

**Comment by tahirs95** [comment]
It works, Thanks.
When I run the script with headless: true, I am getting blocked although tried with proxies, but when I open with headless: false, it works fine. Is there any settings which I need to make?
