### ISSUE TITLE
v1.14.1 ValueError: Unsupported model_provider='groq/xxxxx'

### ISSUE THREAD

**Issue by hamiltonchua** [ScrapeGraphAI/Scrapegraph-ai#587]
**Describe the bug**
I upgraded scapegraphai from 1.13.3 to 1.14.1.
After the upgrade I now get the following error when using groq

ValueError: Unsupported model_provider='groq/llama3_70b_8192'

**Comment by goasleep** [comment]
@hamiltonchua  you can try use to use `model_instance` to replace it. Here are the [doc](https://github.com/ScrapeGraphAI/Scrapegraph-ai/pull/567/files#diff-26f4bfa824f18f28690b594744f1a5dd0d15171b16d28ab4fee630c7f0182a82) for your reference.

**Comment by JINO-ROHIT** [comment]
replace model_provider with model_instance?

**Comment by f-aguzzi** [comment]
We had a merge issue last week which broke the code that handles instancing models from the name you put in the config. We fixed in the latest beta, or at least that was the intention. I'll check it out and let you know.

**Comment by goasleep** [comment]
```
from langchain_groq import ChatGroq

llm_model_instance = ChatGroq(
    GROQ_API_KEY="xxxxx"
    model="llama3_70b_8192",
    ## other config
)

graph_config = {
    "llm": {
        "model_instance": llm_model_instance, 
        "model_tokens": 5000
    },
}
```

**Comment by JINO-ROHIT** [comment]
@goasleep gotcha , this works
