### ISSUE TITLE
IndexError: list index out of range when use SearchGraph

### ISSUE THREAD

**Issue by curibe** [ScrapeGraphAI/Scrapegraph-ai#608]
**Describe the bug**
There is an error: `index out of range` when I use SearchGraph after updating the library to the last version. In the previous version I had installed it was working well

```
    smart_searcher = SearchGraph(prompt=self.prompt, config=self.config)
  File "/Users/cesaruribe/workspace/monadical/vctools/vctools/.venv/lib/python3.10/site-packages/scrapegraphai/graphs/search_graph.py", line 57, in __init__
    super().__init__(prompt, config, schema)
  File "/Users/cesaruribe/workspace/monadical/vctools/vctools/.venv/lib/python3.10/site-packages/scrapegraphai/graphs/abstract_graph.py", line 57, in __init__
    self.llm_model = self._create_llm(config["llm"])
  File "/Users/cesaruribe/workspace/monadical/vctools/vctools/.venv/lib/python3.10/site-packages/scrapegraphai/graphs/abstract_graph.py", line 136, in _create_llm
    llm_params["model"] = split_model_provider[1]
IndexError: list index out of range
```

**To Reproduce**
Run SearchGraph

**Expected behavior**
It must work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS and docker

**Comment by VinciGit00** [comment]
Ok which model are you using?

**Comment by curibe** [comment]
I'm using this  `{'llm': {'model': 'gpt-4o-mini',...}}`

**Comment by lucidlogic** [comment]
I think you need to add the provider to the model now so `openai/gpt-4o-mini`

**Comment by VinciGit00** [comment]
yes we updated yesterday for making more consistent the library. Look at this example [https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/main/examples/openai/smart_scraper_openai.py](url)

**Comment by VinciGit00** [comment]
Hi, I will close the issue, if you have problems please reopen

**Comment by SpiritedAwayLab** [comment]
known_providers = {"openai", "azure_openai", "google_genai", "google_vertexai",
                        "ollama", "oneapi", "nvidia", "groq", "anthropic" "bedrock", "mistralai",
                        "hugging_face", "deepseek", "ernie", "fireworks"}
                        
                        you need to pick up one from this list
