### ISSUE TITLE
DeepSeek demo

### ISSUE THREAD

**Issue by gudufengzhongyipilang** [ScrapeGraphAI/Scrapegraph-ai#609]
**Describe the bug**
When I run File `search_graph_schema_deepseek.py` using my own API Key, an error occurred.

**To Reproduce**
1. Replace my own key in File `search_graph_schema_deepseek.py ` and Run;
2. See error: `Completions.create() got an unexpected keyword argument 'model_provider'` which happend on `search_graph_schema_deepseek.py", line 50, in <module>
    result = search_graph.run()` 

**Desktop (please complete the following information):**
 - OS: Ubuntu20

**Comment by gudufengzhongyipilang** [comment]
I have reviewed [issue#587](https://github.com/ScrapeGraphAI/Scrapegraph-ai/issues/587#issuecomment-2310213499) and made modifications as follows, but it still doesn't work：
```python
from scrapegraphai.models.deepseek import DeepSeek
deepseek_instance = {
    "model": "deepseek/deepseek-chat",
    "base_url": "https://api.deepseek.com/v1",
    "api_key": deepseek_key,
}

llm_model_instance = DeepSeek(**deepseek_instance)

graph_config = {
    "llm": {
        "model_instance": llm_model_instance,
        "model_tokens": 4000
    },
    "verbose": True,
}

# ************************************************
# Create the SearchGraph instance and run it
# ************************************************

search_graph = SearchGraph(
    prompt="向我列举成都著名的小吃",
    config=graph_config,
    schema=Dishes
)

result = search_graph.run()
print(result)
```

**Comment by gudufengzhongyipilang** [comment]
> I have reviewed [issue#587](https://github.com/ScrapeGraphAI/Scrapegraph-ai/issues/587#issuecomment-2310213499) and made modifications as follows, but it still doesn't work：
> 
> ```python
> from scrapegraphai.models.deepseek import DeepSeek
> deepseek_instance = {
>     "model": "deepseek/deepseek-chat",
>     "base_url": "https://api.deepseek.com/v1",
>     "api_key": deepseek_key,
> }
> 
> llm_model_instance = DeepSeek(**deepseek_instance)
> 
> graph_config = {
>     "llm": {
>         "model_instance": llm_model_instance,
>         "model_tokens": 4000
>     },
>     "verbose": True,
> }
> 
> # ************************************************
> # Create the SearchGraph instance and run it
> # ************************************************
> 
> search_graph = SearchGraph(
>     prompt="向我列举成都著名的小吃",
>     config=graph_config,
>     schema=Dishes
> )
> 
> result = search_graph.run()
> print(result)
> ```
-------------------
In this case, I received the following error:
```cmd
cannot pickle '_thread.RLock' object
search_graph_schema_deepseek.py", line 54, in <module>
    search_graph = SearchGraph(
TypeError: cannot pickle '_thread.RLock' object
```

**Comment by VinciGit00** [comment]
are you using a collar notebook?

**Comment by gudufengzhongyipilang** [comment]
> are you using a collar notebook?

No~ I use my laptop to connect to my Linux server via SSH

**Comment by gudufengzhongyipilang** [comment]
> > I have reviewed [issue#587](https://github.com/ScrapeGraphAI/Scrapegraph-ai/issues/587#issuecomment-2310213499) and made modifications as follows, but it still doesn't work：
> > ```python
> > from scrapegraphai.models.deepseek import DeepSeek
> > deepseek_instance = {
> >     "model": "deepseek/deepseek-chat",
> >     "base_url": "https://api.deepseek.com/v1",
> >     "api_key": deepseek_key,
> > }
> > 
> > llm_model_instance = DeepSeek(**deepseek_instance)
> > 
> > graph_config = {
> >     "llm": {
> >         "model_instance": llm_model_instance,
> >         "model_tokens": 4000
> >     },
> >     "verbose": True,
> > }
> > 
> > # ************************************************
> > # Create the SearchGraph instance and run it
> > # ************************************************
> > 
> > search_graph = SearchGraph(
> >     prompt="向我列举成都著名的小吃",
> >     config=graph_config,
> >     schema=Dishes
> > )
> > 
> > result = search_graph.run()
> > print(result)
> > ```
> 
> In this case, I received the following error:
> 
> ```batchfile
> cannot pickle '_thread.RLock' object
> search_graph_schema_deepseek.py", line 54, in <module>
>     search_graph = SearchGraph(
> TypeError: cannot pickle '_thread.RLock' object
> ```

----------

Continue making changes. With reference to 
[commit 546e59abe4f709378f0a30d475134edf0d7b09e5](https://github.com/ScrapeGraphAI/Scrapegraph-ai/pull/376/commits/546e59abe4f709378f0a30d475134edf0d7b09e5), I have made the following improvements to File `scrapegraphai/graphs/search_graph.py` (start with Line 47   maybe):

 ```python
from ..models.deepseek import DeepSeek
def __init__(self, prompt: str, config: dict, schema: Optional[BaseModel] = None):        
        self.max_results = config.get("max_results", 3)

        # if all(isinstance(value, str) for value in config.values()):
        #     self.copy_config = copy(config)
        # else:
        #     self.copy_config = deepcopy(config)

        # Custom deepcopy function to handle non-picklable objects
        def custom_deepcopy(obj, memo=None):
            if memo is None:
                memo = {}

            # 检查是否已经拷贝过该对象
            if id(obj) in memo:
                return memo[id(obj)]

            if isinstance(obj, dict):
                new_dict = {k: custom_deepcopy(v, memo) for k, v in obj.items()}
                memo[id(obj)] = new_dict
                return new_dict
            elif isinstance(obj, list):
                new_list = [custom_deepcopy(v, memo) for v in obj]
                memo[id(obj)] = new_list
                return new_list
            elif isinstance(obj, tuple):
                new_tuple = tuple(custom_deepcopy(v, memo) for v in obj)
                memo[id(obj)] = new_tuple
                return new_tuple
            elif isinstance(obj, DeepSeek):
                # 特殊处理 DeepSeek 对象
                new_obj = DeepSeek(
                    client=obj.client,
                    async_client=obj.async_client,
                    root_client=obj.root_client,
                    root_async_client=obj.root_async_client,
                    model_name=obj.model_name,
                    openai_api_key=obj.openai_api_key,
                    openai_api_base=obj.openai_api_base,
                    openai_proxy=obj.openai_proxy
                )
                memo[id(obj)] = new_obj
                return new_obj
            elif hasattr(obj, '__dict__'):
                new_obj = obj.__class__()
                memo[id(obj)] = new_obj
                for attr in obj.__dict__:
                    setattr(new_obj, attr, custom_deepcopy(getattr(obj, attr), memo))
                return new_obj
            else:
                return obj

        self.copy_config = custom_deepcopy(config)
```
The error: `TypeError: cannot pickle '_thread.RLock' object` disappear.  There is a problem with the structured format of the output. So I change the File `scrapegraphai/nodes/generate_answer_node.py` Line 100 and Line 105:
```python
method="json_mode"
```

The problem with the structured format of the output disappear. But I encountered a new error: `*** pydantic.v1.error_wrappers.ValidationError: 1 validation error for Generation
text
  str type expected (type=type_error.str)`.

I have located the potential issue to the *`_execute_standard`* function in the `scrapegraphai/graphs/base_graph.py` file, but it's too complex and I'm not good at handling it.

**Comment by gudufengzhongyipilang** [comment]
> are you using search_graph_schema_deepseek.py?

Yeah, that's the file. I just replaced my api_key in it.

**Comment by goasleep** [comment]
@VinciGit00  I found the reason. The reason is SearchGraph use deepcopy in config. and the config have model_instance. model_instance has the CookieJar object. the CookieJar object cannot use deepcopy to copy.
<img width="1201" alt="image" src="https://github.com/user-attachments/assets/a2dcb99f-8796-4ca1-bd78-cf982e56547e">

**Comment by goasleep** [comment]
I also find there are other graph use it except it. But seem model_instance and deepcopy are not compatible.

**Comment by VinciGit00** [comment]
we do it for the parallelism and deep copy of instances of graphs, @goasleep do you have any idea of how to fix it?

**Comment by f-aguzzi** [comment]
@gudufengzhongyipilang I might have a fix for the problem with the error `Completions.create() got an unexpected keyword argument 'model_provider'`. It might be related to our recent refactor of the `AbstractGraph`. I'll try to fix it later today.

@goasleep if you found a way to fix the `TypeError: cannot pickle '_thread.RLock' object`, you're officially our hero. We've been having an open issue about it (#374) for a very long time.

**Comment by goasleep** [comment]
@f-aguzzi  I will try fix it later

**Comment by gudufengzhongyipilang** [comment]
> @gudufengzhongyipilang I might have a fix for the problem with the error `Completions.create() got an unexpected keyword argument 'model_provider'`. It might be related to our recent refactor of the `AbstractGraph`. I'll try to fix it later today.
> 
> @goasleep if you found a way to fix the `TypeError: cannot pickle '_thread.RLock' object`, you're officially our hero. We've been having an open issue about it (#374) for a very long time.

Sure, thank you for your hard work and attention.

**Comment by VinciGit00** [comment]
Hi please update to the new version

**Comment by xs818818** [comment]
Requirement already satisfied: scrapegraphai in /usr/local/lib/python3.10/site-packages (1.16.0)
have a error
TypeError: Completions.create() got an unexpected keyword argument 'model_provider'

**Comment by VinciGit00** [comment]
hi please update to the new demo

**Comment by gudufengzhongyipilang** [comment]
> @gudufengzhongyipilang @xs818818 We might have fixed `TypeError: Completions.create() got an unexpected keyword argument 'model_provider'`. Check out the latest beta, it's in there. Let us know if it works or if the problem is still there.

Okay. I will verify it later.

**Comment by gudufengzhongyipilang** [comment]
> hi please update to the new demo

Thank you~
