### ISSUE TITLE
i am getting the below while running for ollama model

### ISSUE THREAD

**Issue by MSR2201** [ScrapeGraphAI/Scrapegraph-ai#616]
Traceback (most recent call last):
  File "D:\Five minutes\firecrawl\scrapegraph\app1.py", line 1, in <module>
    from scrapegraphai.graphs import SmartScraperGraph
  File "D:\Five minutes\firecrawl\scrapegraph\myenv\lib\site-packages\scrapegraphai\graphs\__init__.py", line 5, in <module>
    from .abstract_graph import AbstractGraph
  File "D:\Five minutes\firecrawl\scrapegraph\myenv\lib\site-packages\scrapegraphai\graphs\abstract_graph.py", line 16, in 
<module>
    from ..utils.logging import set_verbosity_warning, set_verbosity_info
  File "D:\Five minutes\firecrawl\scrapegraph\myenv\lib\site-packages\scrapegraphai\utils\__init__.py", line 13, in <module>
  File "D:\Five minutes\firecrawl\scrapegraph\myenv\lib\site-packages\scrapegraphai\utils\convert_to_md.py", line 5, in <module>
    from html2text import HTML2Text
  File "D:\Five minutes\firecrawl\scrapegraph\myenv\lib\site-packages\html2text\__init__.py", line 11, in <module>
    from . import config
ImportError: cannot import name 'config' from partially initialized module 'html2text' (most likely due to a circular import) (D:\Five minutes\firecrawl\scrapegraph\myenv\lib\site-packages\html2text\__init__.py)

ignore the name of the folder the error is persistent what is happening ?

**Comment by VinciGit00** [comment]
ok can you show the code please?

**Comment by MSR2201** [comment]
from scrapegraphai.graphs import SmartScraperGraph
from scrapegraphai.utils import prettify_exec_info

graph_config = {
   "llm": {
      "model": "ollama/gemma2:2b",
      "temperature": 1,
      "format": "json",  # Ollama needs the format to be specified explicitly
      "model_tokens": 100, #  depending on the model set context length
      "base_url": "http://localhost:11434",  # set ollama URL of the local host (YOU CAN CHANGE IT, if you have a different endpoint
   },
   "embeddings": {
      "model": "ollama/nomic-embed-text",
      "temperature": 0,
      "base_url": "http://localhost:11434",  # set ollama URL
   }
}


smart_scraper_graph = SmartScraperGraph(
   prompt="List me all the projects with their description.",
   # also accepts a string with the already downloaded HTML code
   source="https://perinim.github.io/projects",
   config=graph_config
)

result = smart_scraper_graph.run()
print(result)

this is the code which i used

**Comment by VinciGit00** [comment]
Look at the new examples

**Comment by VinciGit00** [comment]
ok what's is your config?
can you try to use llama3?

**Comment by MSR2201** [comment]
my laptop is a cpu based but it should not be a problem with gemma llama is taking too much space

**Comment by infiniti47** [comment]
import json
from scrapegraphai.graphs import SmartScraperGraph
import ollama

# Define the configuration for the scraping pipeline
graph_config = {
    "llm": {
        
        "model": "llama3.1",
    },
    "verbose": True,
    "headless": False,
}

prompt="Find some information about what does the company do, the name and a contact email."
# Create the SmartScraperGraph instance
smart_scraper_graph = SmartScraperGraph(
    config=graph_config, prompt=prompt,source="https://cnn.com/",
)

# Run the pipeline
result = smart_scraper_graph.run()
print(json.dumps(result, indent=4))

I get an error: graphs\abstract_graph.py", line 57, in __init__
    self.llm_model = self._create_llm(config["llm"])
  File "C:\Users\m.sarathi\AppData\Local\anaconda3\envs\partha123\lib\site-packages\scrapegraphai\graphs\abstract_graph.py", line 136, in _create_llm
    llm_params["model"] = split_model_provider[1]
IndexError: list index out of range

**Comment by HimashaHerath** [comment]
were you able to find a solution for this error ?

**Comment by VinciGit00** [comment]
Yes, update the library
