### ISSUE TITLE
When I use examples/deepseek/smart_scraper_deepseek.py ,I have a error.

### ISSUE THREAD

**Issue by xs818818** [ScrapeGraphAI/Scrapegraph-ai#623]
response = self.root_client.beta.chat.completions.parse(**payload)
TypeError: Completions.parse() got an unexpected keyword argument 'model_provider'

**Comment by f-aguzzi** [comment]
Did you try the latest beta (1.17.0b2)? We made a fix that's supposed to prevent this, but we can't test it because we do not have access to DeepSeek API keys.

**Comment by f-aguzzi** [comment]
Wait - beta 2 is broken. We'll get beta 3 out very soon.

**Comment by f-aguzzi** [comment]
This was fixed in #621, so it's released in the beta, but not yet into the stable channel.

**Comment by VinciGit00** [comment]
Hi please update to the new beta
