### ISSUE TITLE
Provider bedrock is not supported when trying to use bedrock examples listed in repo.

### ISSUE THREAD

**Issue by anth0nyhak1m** [ScrapeGraphAI/Scrapegraph-ai#633]
Here is my config, got it off the examples. 

graph_config = {
    "llm": {
        "client": "bedrock",
        "model": "bedrock/anthropic.claude-3-sonnet-20240229-v1:0",
        "temperature": 0.0
    }
}

Clarity on what "client" is helps.

Here is the error:
 line 139, in _create_llm
    raise ValueError(f"Provider {llm_params['model_provider']} is not supported. If possible, try to use a model instance instead.")
ValueError: Provider bedrock is not supported. If possible, try to use a model instance instead.

**Comment by anth0nyhak1m** [comment]
![image](https://github.com/user-attachments/assets/c248b812-d038-46b1-8175-f54ed8c4a0cb)


Looks like the bug is caused because of a missing comma between anthropic and bedrock.

**Comment by f-aguzzi** [comment]
Working on it, thanks for reporting this bug. The fix will most likely be rolled out in the next beta in a few hours.

**Comment by VinciGit00** [comment]
Hi please update to the new beta
