### ISSUE TITLE
Executing RAG Node

### ISSUE THREAD

**Issue by infiniti47** [ScrapeGraphAI/Scrapegraph-ai#638]
When i try to get information from a web page, i only get the URL and some description and maybe contact info. Nothing more.

Output is something like this for the prompt ="List me all the news with their description. Separate them by category.",
   
{
  "title": "WIRED",
  "description": "The essential source of information and ideas that make sense of a world in constant transformation.",
  "url": "https://www.wired.com/",
  "type": "website",
  "keywords": [
    "technology",
    "innovation",
    "science",
    "design"
  ]
}

I see the below executions. Is it because RAG node is not being initiated?  No context being provided to LLM? Please guide.

--- Executing Fetch Node ---
--- (Fetching HTML from: https://www.wired.com/category/science/) ---
--- Executing Parse Node ---
--- Executing GenerateAnswer Node ---

**Comment by VinciGit00** [comment]
Hi the rag node is not used anymore.
Please try to use a schema instead.
You can find it in the example

**Comment by infiniti47** [comment]
Ok thank you
