### ISSUE TITLE
SmartScraperGraph with Gemini: Provider google is not supported in SmartScraperGraph

### ISSUE THREAD

**Issue by moustafa126** [ScrapeGraphAI/Scrapegraph-ai#649]
I encountered an issue while trying to use the SmartScraperGraph from the scrapegraphai.graphs module. The code fails when using the configuration for the llm model provider set to google/gemini-1.5-pro.

import json
from scrapegraphai.graphs import SmartScraperGraph

graph_config = {
    "llm": {
        "api_key": "api_key",
        "model": "google/gemini-1.5-pro"
    },
}

smart_scraper_graph = SmartScraperGraph(
    prompt="Get full details and spacifications of this product ",
    source="https://www.lantechcom.tw/global/eng/software-OS3_OS4.html",
    config=graph_config
)

import nest_asyncio
nest_asyncio.apply()
result = smart_scraper_graph.run()
print(result)

ValueError: Provider google is not supported. If possible, try to use a model instance instead.

**Comment by ekinsenler** [comment]
try `"model": "google_vertexai/gemini-1.5-pro"` instead

**Comment by moustafa126** [comment]
Worked! Thank you so much
