### ISSUE TITLE
return number of input and output tokens with the model

### ISSUE THREAD

**Issue by luisagcrux** [ScrapeGraphAI/Scrapegraph-ai#661]
We would like to request a new feature to track and report token usage when using OpenAI models with ScrapeGraphAI. This would allow users to monitor costs associated with API calls.

Proposed Functionality:
Track prompt tokens used (completion.usage.prompt_tokens)
Track completion tokens used (completion.usage.completion_tokens)
Provide a method to access these token counts after each scraping operation

Suggested Implementation:
Add a token_usage attribute to the scraper object that stores a dictionary with keys for 'prompt_tokens' and 'completion_tokens'
Update this attribute after each API call to OpenAI
Implement a get_token_usage() method that returns the current token usage

Example Implementation

scraper = SmartScraperGraph(prompt="Extract product information", source="https://example.com", config=graph_config)
result = scraper.run()

token_usage = scraper.get_token_usage()
print(f"Prompt tokens: {token_usage['prompt_tokens']}")
print(f"Completion tokens: {token_usage['completion_tokens']}")

**Comment by VinciGit00** [comment]
Look at this example [https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/main/examples/openai/smart_scraper_openai.py](url) at line 45
