### ISSUE TITLE
Cerebras and SambaNova

### ISSUE THREAD

**Issue by amittos** [ScrapeGraphAI/Scrapegraph-ai#666]
[Cerebras](https://inference.cerebras.ai/) and [SambaNova](https://sambanova.ai/) are fast inference solutions similar to Groq. Any chance of supporting them?

**Comment by goasleep** [comment]
@amittos  hello. you can refer this [document](https://scrapegraph-ai.readthedocs.io/en/latest/scrapers/llm.html#other-llm-models). 
Seem this `Cerebras` can be used in this way but `SambaNova` don't implement by langchain.
