### ISSUE TITLE
Is there a possible way to do exception handling for this case. It seems to be an issue with langchain, but I saw some fixes.

### ISSUE THREAD

**Issue by anth0nyhak1m** [ScrapeGraphAI/Scrapegraph-ai#685]
raise OutputParserException(msg, llm_output=text) from e
langchain_core.exceptions.OutputParserException: Invalid json output: Here is the JSON output:

{
"members": "NA"
}

**Comment by VinciGit00** [comment]
Can I see the code?

**Comment by VinciGit00** [comment]
hi, I think it would have been update, if you still have problems reopen the issue

**Comment by anth0nyhak1m** [comment]
Re-opening.

Here is the code.

def ai_scrape_text(text: str, client: object) -> str:
    """
    Scrapes and extracts information from the provided text using an AI-powered SmartScraperGraph.

    This function creates a SmartScraperGraph with a specified prompt, passes the given text and
    client configuration to the graph, and returns the result in a formatted JSON string.

    Args:
        text (str): The input text or webpage content that needs to be analyzed.
        client (object): The client object used to invoke the language model (e.g., AWS Bedrock client).

    Returns:
        str: A formatted JSON string containing the result of the smart scraper graph's run.
    """

    graph_config = {
        "llm": {
            "client": client,
            "model": "bedrock/anthropic.claude-3-sonnet-20240229-v1:0" #"bedrock/meta.llama3-8b-instruct-v1:0"
            }
        }

    smart_scraper_graph = SmartScraperGraph(
        prompt="List the members of the executive suite of this company?",
        source=text,
        config=graph_config
        )

    result = smart_scraper_graph.run()
    return result #json.dumps(result, indent=4)
    
    I saw another post saying use a different LLM, but this is happening with all the bedrock LLMs I am using. Is there a way to solve the deeper core issue? 
    
    {
  "answer": "NA"
}
