### ISSUE TITLE
smart_scraper_graph.run() hangs indefinitely

### ISSUE THREAD

**Issue by anth0nyhak1m** [ScrapeGraphAI/Scrapegraph-ai#696]
Sometimes my script runs to completion, but for the most part, it simply hangs until I interrupt it.

Please help me add some insight into what may be going wrong.

`def ai_scrape_text(text: str, client: object) -> str:
    """
    Scrapes and extracts information from the provided text using an AI-powered SmartScraperGraph.

    This function creates a SmartScraperGraph with a specified prompt, passes the given text and
    client configuration to the graph, and returns the result in a formatted JSON string.

    Args:
        text (str): The input text or webpage content that needs to be analyzed.
        client (object): The client object used to invoke the language model (e.g., AWS Bedrock client).

    Returns:
        str: A formatted JSON string containing the result of the smart scraper graph's run.
    """
    print("waiting 0")
    graph_config = {
        "llm": {
            "client": client,
            "model": "bedrock/anthropic.claude-3-sonnet-20240229-v1:0" #"bedrock/meta.llama3-8b-instruct-v1:0"
            }
        }
    print("waiting 1")
    smart_scraper_graph = SmartScraperGraph(
        prompt=
        """
        List the members of the executive suite of this company.
        If the website content does not list members of the executive suite then return NA.
        Return all responses in a valid JSON output only.
        """,
        source=text,
        config=graph_config
        )
    print("waiting 2")
    result = smart_scraper_graph.run()
    print("waiting 3")
    return result #json.dumps(result, indent=4)

def main(company_url: str) -> None:
    """
    Main function to scrape and analyze a company's website by processing its paragraphs using an AI-powered scraper.

    This function scrapes the text of a company's website, instantiates a Bedrock client for language model inference,
    and processes each paragraph of the scraped content using the AI scraper. It prints the analysis results for
    each paragraph.

    Args:
        company_url (str): The URL of the company's website to be scraped and analyzed.

    Returns:
        None
    """
    file_path = scrape_website_text(company_url)
    bedrock_client = instantiate_bedrock_client()
    for i, text in enumerate(parse_paragraphs_from_file(file_path), start=1):
        print(f"Processing paragraph {i}: {text[:100]}...")
        print(ai_scrape_text(text, bedrock_client))`

**Comment by VinciGit00** [comment]
please update to the new version
