### ISSUE TITLE
ScriptCreatorMultiGraph not working

### ISSUE THREAD

**Issue by justKishore** [ScrapeGraphAI/Scrapegraph-ai#697]
Eg:

script_creator_graph = ScriptCreatorMultiGraph(
    prompt="Who is Marco Perini?",
    source=urls,
    config=graph_config
)

result = script_creator_graph.run()
print(result)

error:
    graph_instance = [graph_instance(
    TypeError: 'ScriptCreatorGraph' object is not callable

**Comment by VinciGit00** [comment]
ok thx I will fix it
