### ISSUE TITLE
ImportError: Could not import transformers python package.

### ISSUE THREAD

**Issue by IvanLee113** [ScrapeGraphAI/Scrapegraph-ai#719]
**Describe the bug**
When running via local llm, ( Llama3.2 ) sometime it succeeded, but sometime it will throw the error below intermittently even when scraping from the exact same URL. 

ImportError: Could not import transformers python package. This is needed in order to calculate get_token_ids. Please install it with `pip install transformers`.

**Comment by VinciGit00** [comment]
ok please show me the code

**Comment by VinciGit00** [comment]
hi please update to the new version

**Comment by IvanLee113** [comment]
Still the same error even after I've updated.

```
graph_config = {
    "llm": {
        "type": "ollama",
        "model": "ollama/llama3.2:1b",
        "format": "json",
        "base_url": "http://192.168.0.13:11434",  # Ollama in Docker
    },

    "embeddings": {
      "model": "ollama/nomic-embed-text",
      "temperature": 0,
      "base_url": "http://192.168.0.13:11434",  # Ollama in Docker
   },
    "verbose": True,
    "headless": True,
}

urls = ["https://www.bbc.com/news/articles/c70w1j0l488o"]

if urls:
    smart_scraper_graph = SmartScraperMultiGraph(
        prompt=scrape_prompt,
        source=urls,
        config=graph_config
    )

    # Run the pipeline
    result = smart_scraper_graph.run()
    #print(result)
    print(json.dumps(result, indent=4))
else:
    print("No search results found.")
```

**Comment by travisvn** [comment]
I'm getting this error as well and cannot find a solution for the life of me

**Comment by Qunlexie** [comment]
I am having the same issue. I will reopen another issue referencing this.
