### ISSUE TITLE
Abt LLM inference

### ISSUE THREAD

**Issue by emreekmekcioglu1** [ScrapeGraphAI/Scrapegraph-ai#721]
Hello thnx for the great work! ı am really excited to use it. I wanted to ask is there a way to make inference with a private llm server. I m using vLLM openai compatible server.
Thnx in advance

**Comment by ekinsenler** [comment]
@emreekmekcioglu1  You can use openai as provider, it should work
`graph_config = {
    "llm": {
        "api_key": "some dummy key",
        "model": "openai/your_model_name",
        "base_url": "your server IP"
    },
   ...
}`
