### ISSUE TITLE
`'FetchNode' object has no attribute 'update_state'`

### ISSUE THREAD

**Issue by mrBlackHat777** [ScrapeGraphAI/Scrapegraph-ai#731]
``` from scrapegraphai.graphs import PDFScraperGraph

# Define the prompt, source, and configuration
prompt = "List me all the attractions in Chioggia."
source = "data/chioggia.pdf"
OPENAI_API_KEY = ""
# Define configuration for PDFScraperGraph with embeddings
config = {
    "llm": {"model": "openai/gpt-3.5-turbo"},
    "verbose": True,
    "headless": False
}

# Create the PDF scraper graph
pdf_scraper = PDFScraperGraph(prompt, source, config)

# Run the PDF scraper graph
result = pdf_scraper.run()

print(result)
```

**Describe the bug**

An `AttributeError` is raised: `'FetchNode' object has no attribute 'update_state'`. This error occurs when trying to run the `PDFScraperGraph` with the specified prompt, source, and configuration.

**To Reproduce**

1. Define a prompt, source, and configuration as shown in the script.
2. Create a `PDFScraperGraph` instance with the defined parameters.
3. Run the `pdf_scraper.run()` method.
4. Observe the error: `'FetchNode' object has no attribute 'update_state'`.

**Expected behavior**

The PDF scraper graph should process the provided PDF file and return a list of attractions in Chioggia without throwing an error.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**

The issue seems to originate from the internal handling of state updates within the `FetchNode` class. Ensuring that the node correctly manages its state or modifying the method to include `update_state` could resolve this problem.

**Comment by VinciGit00** [comment]
hi please open by yourself the pdf and use the mdscraper instead

**Comment by VinciGit00** [comment]
please use DocumentScraperGraph in the beta
