### ISSUE TITLE
Using pre-downloaded HTML

### ISSUE THREAD

**Issue by sky-jo** [ScrapeGraphAI/Scrapegraph-ai#735]
**Describe the bug**

I'm trying to give Scrapegraph AI pre-downloaded HTML (from Selenium) to extract specific data. I want to use this approach to reduce the size of the HTML the LLM needs to parse. It seems like scrapegraph is trying the make a request to download the HTML, but I simply want to give the HTML to the SmartScraperGraph. From what I have seen in the documentation, this should work.

This is the error I get when I run the script shown below. 
```shell
return self.update_state(state, compressed_document)
           ^^^^^^^^^^^^^^^^^
AttributeError: 'FetchNode' object has no attribute 'update_state'
```

This error occurs on the line
```python
result = smart_scraper_graph.run()
```

**To Reproduce**
Here is the script I run that produces the error

from scrapegraphai.graphs import SmartScraperGraph
```python
HTML = '''<div class="product-page-info">
        <h2>Application</h2>
833 is an ashless antiwear additive containing phosphorus and sulfur. It is very effective in many industrial lubricant and 
grease applications where the presence of zinc is undesirable or ineffective.
<hr>
<h2>Key Performance Benefits</h2>

<ul>
	<li>Useful in boosting performance in a variety of tests including TIMKEN,
      4-ball&nbsp;Wear, FZG and Vane Pump in industrial oils</li>
	<li>Especially useful for reducing fretting wear in grease</li>
	<li>Suitable for use with a variety of grease thickeners</li>
	<li>Ashless</li>
	<li>Chlorine-free</li>
	<li>Soluble in mineral and synthetic base oils</li>
</ul>
<hr>
<h2>Recommended Dosage</h2>
HiTEC® 833 may be used between 0.1% wt. and 2.0 % wt. depending on the application. 
Please contact your Afton Chemical representative for specific recommendations.'''

graph_config = {
   "llm": {
      "model": "ollama/mistral",
      "temperature": 1,
      "format": "json",  # Ollama needs the format to be specified explicitly
      "model_tokens": 5000, #  depending on the model set context length
      "base_url": "http://localhost:11434",  # set ollama URL of the local host (YOU CAN CHANGE IT, if you have a different endpoint)
   },
   "embeddings": {
      "model": "ollama/nomic-embed-text",
      "temperature": 0,
      "base_url": "http://localhost:11434",  # set ollama URL
   }
}
smart_scraper_graph = SmartScraperGraph(
    prompt="Get the applications, key performance benefits and recommended dosage",
    source=HTML, # String containing HTML data
    config=graph_config,
)

result = smart_scraper_graph.run()
print(result)
```
**Expected behavior**
I expect this script to extract data from the chunk of HTML I passed as a String into source

**OS and Library Version**
 - OS: Windows 10
 - Scrapegraph AI version 1.25.2

**Comment by zhangtiankuan** [comment]
I meet the same problem

**Comment by VinciGit00** [comment]
use mdscraper instead

**Comment by zhangtiankuan** [comment]
> use mdscraper instead
I use mdscraper instead,but it report the following error

**Comment by mdc-17** [comment]
Hi,

I have tried to apply the change in my code as stated in this issue but I have the following problem... something happened? I can't find anything about MDScraperGraph.

**ImportError: cannot import name 'MDScraperGraph' from 'scrapegraphai.graphs'**

**Comment by gsavvid** [comment]
I think this issue is still open, @VinciGit00. There's no reference of `MDScraperGraph` in the latest version.
