### ISSUE TITLE
Error when using DocumentScraperGraph: AttributeError: 'str' object has no attribute 'page_content'

### ISSUE THREAD

**Issue by 22sauravt** [ScrapeGraphAI/Scrapegraph-ai#746]
import os,json
from dotenv import load_dotenv
from scrapegraphai.graphs import DocumentScraperGraph
from pdfminer.high_level import extract_text

load_dotenv()

# Define the configuration for the graph
graph_config = {
    "llm": {
        "api_key": os.getenv("OPENAI_API_KEY"),  # Use the OpenAI API key
        "model": "openai/gpt-4o-mini",  # Specify the model to use
    },
    "verbose": True,  # Enable verbose mode for detailed output
    "headless": True,  # Run the search in headless mode
}

# Path to your PDF file
pdf_path = 'data/hacker_news.pdf'

doc_scraper_graph = DocumentScraperGraph(
    prompt="Summarize the text and find the main topics",
    source=pdf_path,
    config=graph_config,
)
result = doc_scraper_graph.run()

print(json.dumps(result, indent=4))

**Screenshots**
![image](https://github.com/user-attachments/assets/973e6ce0-f621-45b4-bafb-c59e51cb701a)

**Comment by 22sauravt** [comment]
Version: 1.26.0b16

**Comment by VinciGit00** [comment]
Look document scraper

**Comment by 22sauravt** [comment]
Sorry , I was not able to understand your comment. Can you please explain a little more? Thanks!
