### ISSUE TITLE
Token Sequence Length Exceeds Limit Despite `model_tokens` Parameter in Ollama Model

### ISSUE THREAD

**Issue by JSchmie** [ScrapeGraphAI/Scrapegraph-ai#768]
**Describe the bug**
The `model_tokens` parameter in the `graph_config` dictionary is not being applied to the Ollama model within the `SmartScraperGraph` setup. Despite setting `model_tokens` to 128000, the output still shows an error indicating that the token sequence length exceeds the model's limit (`2231 > 1024`), causing indexing errors.

**To Reproduce**
1. Set up a `SmartScraperGraph` using the code below.
2. Configure the `graph_config` dictionary, specifying `model_tokens: 128000` under the `"llm"` section.
3. Run the scraper with `smart_scraper_graph.run()`.
4. Observe the error regarding token sequence length.

**Expected behavior**
The `model_tokens` parameter should be applied to Ollama's model, ensuring that the model respects the 128000-token length specified without raising indexing errors.

**Code**
```python
from scrapegraphai.graphs import SmartScraperGraph

ollama_base_url = 'http://localhost:11434'
graph_config = {
    "llm": {
        "model": "ollama/mistral",
        "temperature": 1,
        "format": "json",
        'model_tokens': 128000,
        "base_url": ollama_base_url
    },
    "embeddings": {
        "model": "ollama/nomic-embed-text",
        "base_url": ollama_base_url
    },
}

smart_scraper_graph = SmartScraperGraph(
   prompt='What is this website about?',
   source="my.example.com",
   config=graph_config
)
result = smart_scraper_graph.run()
print(result)
```

**Error Message**

```bash
Token indices sequence length is longer than the specified maximum sequence length for this model (2231 > 1024). Running this sequence through the model will result in indexing errors.
```

**Desktop:**

  - OS: Ubuntu 22.04.5 LTS
  - Browser: Chromium
  - Version:
      -  Python 3.12.7
      -  scrapegraphai 1.26.7
      -  Torch 2.5 (Torch should not be necessary as Ollama is being used)

**Additional context:** Ollama typically uses the num_ctx parameter to set context length. It seems that model_tokens does not directly influence the model's context length, suggesting a possible oversight or misconfiguration in how the SmartScraperGraph handles token length parameters with Ollama models.

Thank you for taking the time to look into this issue! I appreciate any guidance or suggestions you can provide to help resolve this problem. Your assistance means a lot, and I'm looking forward to any insights you might have on how to apply the `model_tokens` parameter correctly with Ollama. Thanks again for your help!

**Comment by VinciGit00** [comment]
please update to the new examples

**Comment by VinciGit00** [comment]
they are legacy

**Comment by JSchmie** [comment]
Can you point me towards the latest examples? I followed [this one](https://scrapegraph-ai.readthedocs.io/en/latest/getting_started/examples.html).

**Comment by VinciGit00** [comment]
look at this link [https://github.com/ScrapeGraphAI/Scrapegraph-ai/tree/main/examples](url)

**Comment by JSchmie** [comment]
> look at this link [https://github.com/ScrapeGraphAI/Scrapegraph-ai/tree/main/examples](url)

I've looked into the examples, and I noticed that in [this example](https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/eb24da5a8d3bd56fcbfadbb63e3536d8c2e87dde/examples/local_models/json_scraper_multi_ollama.py#L13) and other examples related to Ollama, the context window is set using `model_tokens`. However, in the example for [simple web scraping](https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/main/examples/local_models/smart_scraper_ollama.py), the context window isn’t modified at all.

I really like your project, but without being able to increase the context window to make full use of the model, I won’t be able to use this framework effectively. Could you please provide a short code snippet or guidance on changing the context length in the latest version?

**Comment by VinciGit00** [comment]
ok, can you specify the context_window inside? like this graph_config = {
    "llm": {
        "model": "ollama/mistral",
        "temperature": 1,
        "format": "json",
        'model_tokens': 128000,
        "base_url": ollama_base_url
    }

**Comment by VinciGit00** [comment]
Btw which model of mistral are you using? 
These are the available models https://ollama.com/library/mistral

**Comment by JSchmie** [comment]
> ok, can you specify the context_window inside? like this graph_config = { "llm": { "model": "ollama/mistral", "temperature": 1, "format": "json", 'model_tokens': 128000, "base_url": ollama_base_url }

As you can see from my example, I followed this procedure. I attempted to execute it without embedding for debugging purposes, however, the identical error persists.  I am using ollama version 0.3.14. 

> Btw which model of mistral are you using? These are the available models https://ollama.com/library/mistral

I just use the latest model of mistral, but I also tried llama3.1:8b and 70b which has a context length of 128k and also the gemma2:9b.

**Comment by f-aguzzi** [comment]
@JSchmie I fixed this in #773. The `model_tokens` dictionary key was only available with model instances before this, but now it's accessible for all models.

The pull request will be merged into the development branch (`pre/beta`) first, so a few days will pass before the fix will be available in a stable release.

**Comment by JSchmie** [comment]
> @JSchmie I fixed this in #773. The `model_tokens` dictionary key was only available with model instances before this, but now it's accessible for all models.
> 
> The pull request will be merged into the development branch (`pre/beta`) first, so a few days will pass before the fix will be available in a stable release.

I have installed your branch using. 
```bash
pip install --force-reinstall git+https://github.com/ScrapeGraphAI/Scrapegraph-ai.git@768-fix-model-tokens
```
But unfortunately, I cannot confirm that it works. I still get the error: 

```bash
Token indices sequence length is longer than the specified maximum sequence length for this model (11148 > 1024). Running this sequence through the model will result in indexing errors
```

I can confirm that `self.model_token` is set to 128000. Furthermore, I also tried to set `llm_params["num_ctx"] = self.model_token` [here](https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/f79f399ee0d660f162e0cb96d9faba48ecdc88b2/scrapegraphai/graphs/abstract_graph.py#L172C1-L172C57) since `ChatOllama` also uses `num_ctx` to set the context window ([see documentation here](https://python.langchain.com/api_reference/ollama/chat_models/langchain_ollama.chat_models.ChatOllama.html#langchain_ollama.chat_models.ChatOllama.num_ctx)).

**Comment by VinciGit00** [comment]
hi please update to the new beta

**Comment by JSchmie** [comment]
@VinciGit00 I tried that adjustment, and while the error persists:

```
Token indices sequence length is longer than the specified maximum sequence length for this model (11148 > 1024). Running this sequence through the model will result in indexing errors
```
the results are looking significantly better now! Could it be that this error is being thrown unintentionally?

**Comment by f-aguzzi** [comment]
@JSchmie the error is coming from LangChain and not from ScrapeGraphAI. Using `ollama/mistral` will call Mistral 7B, which has a context window of 1024 tokens.

**Comment by JSchmie** [comment]
Yes, but the error still occurs when I am using: 

```python
graph_config = {
    "llm": {
        "model": "ollama/llama3.1:8b",
        "temperature": 1,
        "format": "json",
        'model_tokens' : 128000, 
        "base_url": ollama_base_url 
    },
    "embeddings": {
        "model": "ollama/nomic-embed-text",
        "base_url": ollama_base_url 
    },
}
```

**Comment by JSchmie** [comment]
**Update:**

I believe I found a crucial issue, which may stem from Ollama itself. In their [API documentation](https://github.com/ollama/ollama/blob/main/docs/api.md), they note:

> **Important:**  
> When `format` is set to `json`, the output will always be a well-formed JSON object. It’s essential to also instruct the model to respond in JSON.

Until now, I wasn't aware of this limitation. If the model doesn’t respond in JSON, it outputs a series of newline characters. Given that inputs can sometimes be quite large, the model might ignore the instruction to respond in JSON, potentially leading to significant quality discrepancies.

Interestingly, when using LangChain directly, this issue doesn’t occur, and the context length is applied correctly. I’ve included the code below, which may be helpful for debugging.

```python
import requests
from bs4 import BeautifulSoup
from langchain_ollama import ChatOllama

# Define the URL to fetch content from
url = "https://github.com/ScrapeGraphAI/Scrapegraph-ai"

# Send a GET request to fetch the raw HTML content from the URL
response = requests.get(url)
response.raise_for_status()  # Raise an exception if an HTTP error occurs

# Parse the HTML content with BeautifulSoup
soup = BeautifulSoup(response.content, "html.parser")

# Extract and clean up text content from HTML, removing tags and adding line breaks
text_content = soup.get_text(separator='\n', strip=True)

# Create a prompt to ask the language model (LLM) what the website is about
# JSON format is explicitly requested in the prompt
promt = f"""
        USE JSON!!!
        What is this website about?
        {text_content}
        """

# Initialize the language model with specific configurations
llm = ChatOllama(
    base_url='http://localhost:11434',  # Specify the base URL for the LLM server
    model='llama3.1:8b',               # Define the model to use
    num_ctx=128000,                    # Set the maximum context length for the LLM
    format='json'                      # Request JSON output format from the LLM
)

# Invoke the LLM with the prompt and print its response
print(llm.invoke(promt))
```

The output looks like this: 

AIMessage(content='{ "type": "json", "result": { "website": "scrapegraphai.com", "library_name": "ScrapeGraphAI", "description": "A Python library for scraping leveraging large language models.", "license": "MIT license" } }\n\n  \n\n\n\n\n\n  \n\n\n\n  ', additional_kwargs={}, response_metadata={'model': 'llama3.1:8b', 'created_at': '2024-10-29T13:35:28.025049704Z', 'message': {'role': 'assistant', 'content': ''}, 'done_reason': 'stop', 'done': True, 'total_duration': 5262412590, 'load_duration': 4070193548, 'prompt_eval_count': 2328, 'prompt_eval_duration': 385116000, 'eval_count': 61, 'eval_duration': 761894000}, id='run-34027abd-c2ea-433e-8eb5-3bb57b5e97a2-0', usage_metadata={'input_tokens': 2328, 'output_tokens': 61, 'total_tokens': 2389})

**Comment by kolergy** [comment]
I'm with scrapegraphai 1.34.1  and an installed Ollama 0.5.4 
I'm using qwen2.5:14b and nomic-embed-text with 
"model_tokens" : 10000, and "format": "json",
on https://www.wired.com
and I get:
--- Executing ParseNode Node ---
Token indices sequence length is longer than the specified maximum sequence length for this model (6731 > 1024). Running this sequence through the model will result in indexing errors
--- Executing GenerateAnswer Node ---
