### ISSUE TITLE
 RuntimeError: asyncio.run() cannot be called from a running event loop

### ISSUE THREAD

**Issue by boral** [ScrapeGraphAI/Scrapegraph-ai#771]
While running Readme example facing this

'''
result = smart_scraper_graph.run()
--- Executing Fetch Node ---
--- (Fetching HTML from: https://scrapegraphai.com/) ---
Traceback (most recent call last):

  Cell In[5], line 1
    result = smart_scraper_graph.run()

  File ~\anaconda3\envs\test\Lib\site-packages\scrapegraphai\graphs\smart_scraper_graph.py:114 in run
    self.final_state, self.execution_info = self.graph.execute(inputs)

  File ~\anaconda3\envs\test\Lib\site-packages\scrapegraphai\graphs\base_graph.py:263 in execute
    return self._execute_standard(initial_state)

  File ~\anaconda3\envs\test\Lib\site-packages\scrapegraphai\graphs\base_graph.py:184 in _execute_standard
    raise e

  File ~\anaconda3\envs\test\Lib\site-packages\scrapegraphai\graphs\base_graph.py:168 in _execute_standard
    result = current_node.execute(state)

  File ~\anaconda3\envs\test\Lib\site-packages\scrapegraphai\nodes\fetch_node.py:126 in execute
    return self.handle_web_source(state, source)

  File ~\anaconda3\envs\test\Lib\site-packages\scrapegraphai\nodes\fetch_node.py:284 in handle_web_source
    document = loader.load()

  File ~\anaconda3\envs\test\Lib\site-packages\langchain_core\document_loaders\base.py:31 in load
    return list(self.lazy_load())

  File ~\anaconda3\envs\test\Lib\site-packages\scrapegraphai\docloaders\chromium.py:111 in lazy_load
    html_content = asyncio.run(scraping_fn(url))

  File ~\anaconda3\envs\test\Lib\asyncio\runners.py:186 in run
    raise RuntimeError(

RuntimeError: asyncio.run() cannot be called from a running event loop
'''

**Comment by VinciGit00** [comment]
Are you using collab?

**Comment by boral** [comment]
No Spyder

**Comment by f-aguzzi** [comment]
Take a look at the first two code blocks in [the Colab example](https://colab.research.google.com/drive/1sEZBonBMGP44CtO6GQTwAlL0BGJXjtfd?usp=sharing), the ones about `nest_asyncio`. Even though you're using Spyder, it's still a Jupyter Notebook, so the fix should be the same.

**Comment by VinciGit00** [comment]
you should run this [https://colab.research.google.com/drive/1sEZBonBMGP44CtO6GQTwAlL0BGJXjtfd?usp=sharing](url)

**Comment by VianneyMI** [comment]
> https://colab.research.google.com/drive/1sEZBonBMGP44CtO6GQTwAlL0BGJXjtfd?usp=sharing

Yes it works on the colab but it does not work locally on my Jupyter Notebook
