### ISSUE TITLE
Rye is being phased out in favor of uv

### ISSUE THREAD

**Issue by f-aguzzi** [ScrapeGraphAI/Scrapegraph-ai#776]
**Is your feature request related to a problem? Please describe.**
`rye` was taken over by Astral and is still maintained, but is being phased out in favor of `uv`, another Astral project. `uv` is the package manager that `rye` already uses under the hood. See [here](https://rye.astral.sh/) and [here](https://lucumr.pocoo.org/2024/2/15/rye-grows-with-uv/) for info.

**Describe the solution you'd like**
Switch from `rye` to `uv`, which should be painless because they use the same commands and should work very similarly.

**Describe alternatives you've considered**
Keep `rye`for the time being, since it will still be maintained for a while. However, it was adopted when it still was new and not mature, mainly for its long-term potential, and that potential has been taken away. It should not make much of a difference if ScrapeGraphAI remains in its current slow maintenance slumber, but it might be a problem in the long run.

**Comment by madguy02** [comment]
@VinciGit00 i can pick this up

**Comment by VinciGit00** [comment]
Did it in the new version of pre/beta
