### ISSUE TITLE
Timeout in LLM inference - Hanging state

### ISSUE THREAD

**Issue by ekmekovski** [ScrapeGraphAI/Scrapegraph-ai#798]
**Describe the bug**
When the server running the LLM endpoint is down the library cannot create a timeout exception, it is just entering to hanging state. It just print the debug infot --Executing GenerateAnswer Node-- but there is no time out here. 
**To Reproduce**
1. Close the LLM server
2. Try to make inference via scrapegraph ai

**Expected behavior**
I cannot find a timeout parameter for the LLM inference, not the timeout for scraping the web page

**Comment by VinciGit00** [comment]
hi, I will add as soon as possible

**Comment by VinciGit00** [comment]
hi please update to the new beta
