### ISSUE TITLE
Model not found when using Anthropic

### ISSUE THREAD

**Issue by matheus-rossi** [ScrapeGraphAI/Scrapegraph-ai#813]
Version: scrapegraphai@v1.31.0

Issue: Error encountered while using Anthropics models.

Problem: Despite receiving an error message, the process appears to function correctly. Is this something to be concerned about?

**Describe the bug**

```
Model anthropic/claude-3-5-haiku-latest not found,
                    using default token size (8192)
```

**Code**

```
 config = "llm": {
      "api_key": settings.ANTHROPIC_API_KEY,
      "model": "anthropic/claude-3-5-haiku-latest",
      "timeout": 120,
      "temperature": 0,
      "max_tokens": 8192
  },
  "verbose": verbose
}
```

or

```
 config = "llm": {
      "api_key": settings.ANTHROPIC_API_KEY,
      "model": "anthropic/claude-3-5-haiku-claude-3-5-haiku-20241022",
      "timeout": 120,
      "temperature": 0,
      "max_tokens": 8192
  },
  "verbose": verbose
}
```

**Comment by VinciGit00** [comment]
Hi @matheus-rossi  the reason that in this file [https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/813-model-not-found-when-using-anthropic/scrapegraphai/helpers/models_tokens.py](url) the model was not present, if you have any other model that is missing feel free to add it

**Comment by matheus-rossi** [comment]
> Hi @matheus-rossi the reason that in this file [https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/813-model-not-found-when-using-anthropic/scrapegraphai/helpers/models_tokens.py](url) the model was not present, if you have any other model that is missing feel free to add it

Thank you
I will add these models and create a PR

**Comment by VinciGit00** [comment]
hi please update to the new beta

**Comment by VinciGit00** [comment]
Hi @matheus-rossi please let me know
