### ISSUE TITLE
Can not import SmartScraperGraph

### ISSUE THREAD

**Issue by Koutilya-Pande** [ScrapeGraphAI/Scrapegraph-ai#839]
from .chromium import ChromiumLoader
  File "C:\Users\kouti\OneDrive\Desktop\Lexmark\venv\Lib\site-packages\scrapegraphai\docloaders\chromium.py", line 142
    async def ascrape_with_js_support(self, url: str) -> str:
IndentationError: expected an indented block after 'if' statement on line 139

**Comment by Koutilya-Pande** [comment]
Chroumium Loader Function: 
 except (aiohttp.ClientError, asyncio.TimeoutError, Exception) as e:
                attempt += 1
                logger.error(f"Attempt {attempt} failed: {e}")
                if attempt == self.RETRY_LIMIT:
                    raise RuntimeError(
                        f"Failed to fetch {url} after {self.RETRY_LIMIT} attempts: {e}"
                    )
            *finally*:
                *if "browser" in locals():*
{{{This is empty}}}

**Comment by VinciGit00** [comment]
which version are you  using?

**Comment by duongtuanqb** [comment]
There is a syntax error on line 139 in chromium.py, the 'if' statement is not properly closed.
https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/main/scrapegraphai/docloaders/chromium.py#L139

**Comment by aleenprd** [comment]
Lol this needs a quick fix!! @aflansburg what was the intent with that line?

**Comment by linuer** [comment]
In addition to this problem
scrapegraph-py also does not match the 1.33.0 version（scrapegraphai）
 @aflansburg  quick、quick

**Comment by duongtuanqb** [comment]
@VinciGit00 In the file [smart_scraper_graph.py](https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/main/scrapegraphai/graphs/smart_scraper_graph.py#L17), the SyncClient module is used, but it is not found in the file [init.py](https://github.com/ScrapeGraphAI/scrapegraph-sdk/blob/main/scrapegraph-py/scrapegraph_py/__init__.py).

**Comment by aflansburg** [comment]
> There is a syntax error on line 139 in chromium.py, the 'if' statement is not properly closed.

good Lord I must have hit backspace and walked away and come back and committed that 🫠 
I tested that one and it was working.

On the other issue let me check my branch and see i.e. `scrapegraph-py also does not match the 1.33.0`

**Comment by aflansburg** [comment]
> In addition to this problem scrapegraph-py also does not match the 1.33.0 version（scrapegraphai） @aflansburg quick、quick

this looks like a separate issue right? Maybe from introduction of `uv` ?
What is scrapegraph-py?

**Comment by aflansburg** [comment]
@VinciGit00 @aleenprd @duongtuanqb check my fork - this commit seems to fix the issue:

https://github.com/ScrapeGraphAI/Scrapegraph-ai/commit/3214537342dea82c180e7a508b592d0458cd2183

**Comment by aflansburg** [comment]
happy to open PR to pre/beta but @VinciGit00 figured you'd want to get this in faster.

**Comment by VinciGit00** [comment]
Hi guys, I updated to anew main version

**Comment by aflansburg** [comment]
> Hi guys, I updated to anew main version

Working great with new patch ! Thanks!

**Comment by VinciGit00** [comment]
Tutto è bene quel che finisce bene

**Comment by linuer** [comment]
[1.33.2](https://github.com/ScrapeGraphAI/Scrapegraph-ai/compare/v1.33.1...v1.33.2) (2024-12-06)
Fixed this issue
@aflansburg
