### ISSUE TITLE
Example from README.md results in NA description

### ISSUE THREAD

**Issue by 1beb** [ScrapeGraphAI/Scrapegraph-ai#843]
**Describe the bug**
Example from README.md results in NA description

**To Reproduce**

1. Follow the README instructions.

**Expected behavior**

Expected the description or something similar to it as shown in README 

**Screenshots**

![image](https://github.com/user-attachments/assets/feb96b4b-8f4c-4d1a-9707-2a0c7d710a85)

**Desktop (please complete the following information):**
- Ubuntu 22.04

**Comment by VinciGit00** [comment]
Thank you for the feedbacks guys :)
